/* Generated by Yosys 0.52+63 (git sha1 7f7ad87b7, clang++ 18.1.3 -fPIC -O3) */

(* src = "../../../../source/fir8.v:11.1-61.10" *)
module fir8(clk, Xin, Xout, Yin, Yout);
  (* src = "../../../../source/fir8.v:22.13-22.14" *)
  wire [7:0] \C[0] ;
  (* src = "../../../../source/fir8.v:22.13-22.14" *)
  wire [7:0] \C[1] ;
  (* src = "../../../../source/fir8.v:22.13-22.14" *)
  wire [7:0] \C[2] ;
  (* src = "../../../../source/fir8.v:22.13-22.14" *)
  wire [7:0] \C[3] ;
  (* src = "../../../../source/fir8.v:22.13-22.14" *)
  wire [7:0] \C[4] ;
  (* src = "../../../../source/fir8.v:22.13-22.14" *)
  wire [7:0] \C[5] ;
  (* src = "../../../../source/fir8.v:22.13-22.14" *)
  wire [7:0] \C[6] ;
  (* src = "../../../../source/fir8.v:22.13-22.14" *)
  wire [7:0] \C[7] ;
  (* src = "../../../../source/fir8.v:18.13-18.14" *)
  wire [7:0] \X[0] ;
  (* src = "../../../../source/fir8.v:18.13-18.14" *)
  wire [7:0] \X[1] ;
  (* src = "../../../../source/fir8.v:18.13-18.14" *)
  wire [7:0] \X[2] ;
  (* src = "../../../../source/fir8.v:18.13-18.14" *)
  wire [7:0] \X[3] ;
  (* src = "../../../../source/fir8.v:18.13-18.14" *)
  wire [7:0] \X[4] ;
  (* src = "../../../../source/fir8.v:18.13-18.14" *)
  wire [7:0] \X[5] ;
  (* src = "../../../../source/fir8.v:18.13-18.14" *)
  wire [7:0] \X[6] ;
  (* src = "../../../../source/fir8.v:18.13-18.14" *)
  wire [7:0] \X[7] ;
  (* src = "../../../../source/fir8.v:18.13-18.14" *)
  wire [7:0] \X[8] ;
  (* src = "../../../../source/fir8.v:13.17-13.20" *)
  input [7:0] Xin;
  wire [7:0] Xin;
  (* src = "../../../../source/fir8.v:14.17-14.21" *)
  output [7:0] Xout;
  wire [7:0] Xout;
  (* src = "../../../../source/fir8.v:19.13-19.14" *)
  wire [15:0] \Y[0] ;
  (* src = "../../../../source/fir8.v:19.13-19.14" *)
  wire [15:0] \Y[1] ;
  (* src = "../../../../source/fir8.v:19.13-19.14" *)
  wire [15:0] \Y[2] ;
  (* src = "../../../../source/fir8.v:19.13-19.14" *)
  wire [15:0] \Y[3] ;
  (* src = "../../../../source/fir8.v:19.13-19.14" *)
  wire [15:0] \Y[4] ;
  (* src = "../../../../source/fir8.v:19.13-19.14" *)
  wire [15:0] \Y[5] ;
  (* src = "../../../../source/fir8.v:19.13-19.14" *)
  wire [15:0] \Y[6] ;
  (* src = "../../../../source/fir8.v:19.13-19.14" *)
  wire [15:0] \Y[7] ;
  (* src = "../../../../source/fir8.v:19.13-19.14" *)
  wire [15:0] \Y[8] ;
  (* src = "../../../../source/fir8.v:15.17-15.20" *)
  input [15:0] Yin;
  wire [15:0] Yin;
  (* src = "../../../../source/fir8.v:16.17-16.21" *)
  output [15:0] Yout;
  wire [15:0] Yout;
  (* src = "../../../../source/fir8.v:12.17-12.20" *)
  input clk;
  wire clk;
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../source/fir8.v:48.12-48.95" *)
  fir_pe u_fir_pe0 (
    .Cin(8'h04),
    .Xin(Xin),
    .Xout(\X[1] ),
    .Yin(Yin),
    .Yout(\Y[1] ),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../source/fir8.v:49.12-49.95" *)
  fir_pe u_fir_pe1 (
    .Cin(8'h0c),
    .Xin(\X[1] ),
    .Xout(\X[2] ),
    .Yin(\Y[1] ),
    .Yout(\Y[2] ),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../source/fir8.v:50.12-50.95" *)
  fir_pe u_fir_pe2 (
    .Cin(8'h19),
    .Xin(\X[2] ),
    .Xout(\X[3] ),
    .Yin(\Y[2] ),
    .Yout(\Y[3] ),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../source/fir8.v:51.12-51.95" *)
  fir_pe u_fir_pe3 (
    .Cin(8'h22),
    .Xin(\X[3] ),
    .Xout(\X[4] ),
    .Yin(\Y[3] ),
    .Yout(\Y[4] ),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../source/fir8.v:52.12-52.95" *)
  fir_pe u_fir_pe4 (
    .Cin(8'h22),
    .Xin(\X[4] ),
    .Xout(\X[5] ),
    .Yin(\Y[4] ),
    .Yout(\Y[5] ),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../source/fir8.v:53.12-53.95" *)
  fir_pe u_fir_pe5 (
    .Cin(8'h19),
    .Xin(\X[5] ),
    .Xout(\X[6] ),
    .Yin(\Y[5] ),
    .Yout(\Y[6] ),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../source/fir8.v:55.12-55.95" *)
  fir_pe u_fir_pe6 (
    .Cin(8'h04),
    .Xin(\X[7] ),
    .Xout(Xout),
    .Yin(\Y[7] ),
    .Yout(Yout),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../source/fir8.v:54.12-54.95" *)
  fir_pe u_fir_pe7 (
    .Cin(8'h0c),
    .Xin(\X[6] ),
    .Xout(\X[7] ),
    .Yin(\Y[6] ),
    .Yout(\Y[7] ),
    .clk(clk)
  );
  assign \C[0]  = 8'h04;
  assign \C[1]  = 8'h0c;
  assign \C[2]  = 8'h19;
  assign \C[3]  = 8'h22;
  assign \C[4]  = 8'h22;
  assign \C[5]  = 8'h19;
  assign \C[6]  = 8'h0c;
  assign \C[7]  = 8'h04;
  assign \X[0]  = Xin;
  assign \X[8]  = Xout;
  assign \Y[0]  = Yin;
  assign \Y[8]  = Yout;
endmodule

(* top =  1  *)
(* src = "../../../fir8_wrapper.v:6.1-57.10" *)
module fir8_wrapper(Din_emu, Dout_emu, Addr_emu, load_emu, get_emu, clk_emu, clk_dut);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  (* force_downto = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:137.23-137.24" *)
  wire [7:0] _007_;
  (* unused_bits = "2" *)
  wire [2:0] _008_;
  wire [7:0] _009_;
  wire [7:0] _010_;
  wire _011_;
  wire _012_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _013_;
  (* src = "../../../fir8_wrapper.v:9.21-9.29" *)
  input [2:0] Addr_emu;
  wire [2:0] Addr_emu;
  (* src = "../../../fir8_wrapper.v:7.21-7.28" *)
  input [7:0] Din_emu;
  wire [7:0] Din_emu;
  (* src = "../../../fir8_wrapper.v:8.21-8.29" *)
  output [7:0] Dout_emu;
  wire [7:0] Dout_emu;
  (* src = "../../../fir8_wrapper.v:21.17-21.20" *)
  wire [7:0] Xin;
  (* src = "../../../fir8_wrapper.v:24.17-24.21" *)
  wire [7:0] Xout;
  (* src = "../../../fir8_wrapper.v:22.17-22.20" *)
  wire [15:0] Yin;
  (* src = "../../../fir8_wrapper.v:25.17-25.21" *)
  wire [15:0] Yout;
  (* src = "../../../fir8_wrapper.v:11.21-11.28" *)
  input clk_dut;
  wire clk_dut;
  (* src = "../../../fir8_wrapper.v:10.40-10.47" *)
  input clk_emu;
  wire clk_emu;
  (* src = "../../../fir8_wrapper.v:10.31-10.38" *)
  input get_emu;
  wire get_emu;
  (* src = "../../../fir8_wrapper.v:10.21-10.29" *)
  input load_emu;
  wire load_emu;
  wire [7:0] \stimIn[0] ;
  wire [7:0] \stimIn[1] ;
  wire [7:0] \stimIn[2] ;
  (* src = "../../../fir8_wrapper.v:17.17-17.24" *)
  wire [7:0] \vectOut[0] ;
  (* src = "../../../fir8_wrapper.v:17.17-17.24" *)
  wire [7:0] \vectOut[1] ;
  (* src = "../../../fir8_wrapper.v:17.17-17.24" *)
  wire [7:0] \vectOut[2] ;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _014_ (
    .I0(_013_[1]),
    .I1(_013_[0]),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _015_ (
    .I0(_013_[0]),
    .I1(_013_[1]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042304204)
  ) _016_ (
    .I0(\vectOut[1] [0]),
    .I1(\vectOut[0] [0]),
    .I2(\vectOut[2] [0]),
    .I3(_013_[2]),
    .I4(_013_[3]),
    .O(_007_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _017_ (
    .I0(\vectOut[0] [1]),
    .I1(\vectOut[1] [1]),
    .I2(\vectOut[2] [1]),
    .I3(_013_[2]),
    .I4(_013_[3]),
    .O(_007_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _018_ (
    .I0(\vectOut[0] [2]),
    .I1(\vectOut[1] [2]),
    .I2(\vectOut[2] [2]),
    .I3(_013_[2]),
    .I4(_013_[3]),
    .O(_007_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _019_ (
    .I0(\vectOut[0] [3]),
    .I1(\vectOut[1] [3]),
    .I2(\vectOut[2] [3]),
    .I3(_013_[2]),
    .I4(_013_[3]),
    .O(_007_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _020_ (
    .I0(\vectOut[0] [4]),
    .I1(\vectOut[1] [4]),
    .I2(\vectOut[2] [4]),
    .I3(_013_[2]),
    .I4(_013_[3]),
    .O(_007_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _021_ (
    .I0(\vectOut[0] [5]),
    .I1(\vectOut[1] [5]),
    .I2(\vectOut[2] [5]),
    .I3(_013_[2]),
    .I4(_013_[3]),
    .O(_007_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _022_ (
    .I0(\vectOut[0] [6]),
    .I1(\vectOut[1] [6]),
    .I2(\vectOut[2] [6]),
    .I3(_013_[2]),
    .I4(_013_[3]),
    .O(_007_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _023_ (
    .I0(\vectOut[0] [7]),
    .I1(\vectOut[1] [7]),
    .I2(\vectOut[2] [7]),
    .I3(_013_[2]),
    .I4(_013_[3]),
    .O(_007_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0001)
  ) _024_ (
    .I0(_013_[0]),
    .I1(_013_[1]),
    .I2(_013_[2]),
    .I3(_013_[3]),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _025_ (
    .I0(_013_[0]),
    .I1(_013_[1]),
    .I2(_013_[3]),
    .I3(_013_[2]),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _026_ (
    .I0(_013_[0]),
    .I1(_013_[1]),
    .I2(_013_[2]),
    .I3(_013_[3]),
    .O(_004_)
  );
  BUFG _027_ (
    .I(_005_),
    .O(_011_)
  );
  BUFG _028_ (
    .I(_006_),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _029_ (
    .C(_012_),
    .CE(_002_),
    .D(_009_[0]),
    .Q(\stimIn[0] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _030_ (
    .C(_012_),
    .CE(_002_),
    .D(_009_[1]),
    .Q(\stimIn[0] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _031_ (
    .C(_012_),
    .CE(_002_),
    .D(_009_[2]),
    .Q(\stimIn[0] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _032_ (
    .C(_012_),
    .CE(_002_),
    .D(_009_[3]),
    .Q(\stimIn[0] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _033_ (
    .C(_012_),
    .CE(_002_),
    .D(_009_[4]),
    .Q(\stimIn[0] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _034_ (
    .C(_012_),
    .CE(_002_),
    .D(_009_[5]),
    .Q(\stimIn[0] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _035_ (
    .C(_012_),
    .CE(_002_),
    .D(_009_[6]),
    .Q(\stimIn[0] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _036_ (
    .C(_012_),
    .CE(_002_),
    .D(_009_[7]),
    .Q(\stimIn[0] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _037_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[0] [0]),
    .Q(Xin[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _038_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[0] [1]),
    .Q(Xin[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _039_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[0] [2]),
    .Q(Xin[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _040_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[0] [3]),
    .Q(Xin[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _041_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[0] [4]),
    .Q(Xin[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _042_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[0] [5]),
    .Q(Xin[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _043_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[0] [6]),
    .Q(Xin[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _044_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[0] [7]),
    .Q(Xin[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _045_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[1] [0]),
    .Q(Yin[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _046_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[1] [1]),
    .Q(Yin[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _047_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[1] [2]),
    .Q(Yin[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _048_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[1] [3]),
    .Q(Yin[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _049_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[1] [4]),
    .Q(Yin[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _050_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[1] [5]),
    .Q(Yin[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _051_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[1] [6]),
    .Q(Yin[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _052_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[1] [7]),
    .Q(Yin[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _053_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[2] [0]),
    .Q(Yin[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _054_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[2] [1]),
    .Q(Yin[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _055_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[2] [2]),
    .Q(Yin[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _056_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[2] [3]),
    .Q(Yin[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _057_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[2] [4]),
    .Q(Yin[12]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _058_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[2] [5]),
    .Q(Yin[13]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _059_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[2] [6]),
    .Q(Yin[14]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _060_ (
    .C(_012_),
    .CE(_013_[1]),
    .D(\stimIn[2] [7]),
    .Q(Yin[15]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _061_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[8]),
    .Q(\vectOut[2] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _062_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[9]),
    .Q(\vectOut[2] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _063_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[10]),
    .Q(\vectOut[2] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _064_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[11]),
    .Q(\vectOut[2] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _065_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[12]),
    .Q(\vectOut[2] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _066_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[13]),
    .Q(\vectOut[2] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _067_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[14]),
    .Q(\vectOut[2] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _068_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[15]),
    .Q(\vectOut[2] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _069_ (
    .C(_012_),
    .CE(_004_),
    .D(_009_[0]),
    .Q(\stimIn[2] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _070_ (
    .C(_012_),
    .CE(_004_),
    .D(_009_[1]),
    .Q(\stimIn[2] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _071_ (
    .C(_012_),
    .CE(_004_),
    .D(_009_[2]),
    .Q(\stimIn[2] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _072_ (
    .C(_012_),
    .CE(_004_),
    .D(_009_[3]),
    .Q(\stimIn[2] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _073_ (
    .C(_012_),
    .CE(_004_),
    .D(_009_[4]),
    .Q(\stimIn[2] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _074_ (
    .C(_012_),
    .CE(_004_),
    .D(_009_[5]),
    .Q(\stimIn[2] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _075_ (
    .C(_012_),
    .CE(_004_),
    .D(_009_[6]),
    .Q(\stimIn[2] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _076_ (
    .C(_012_),
    .CE(_004_),
    .D(_009_[7]),
    .Q(\stimIn[2] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _077_ (
    .C(_012_),
    .CE(_003_),
    .D(_009_[0]),
    .Q(\stimIn[1] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _078_ (
    .C(_012_),
    .CE(_003_),
    .D(_009_[1]),
    .Q(\stimIn[1] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _079_ (
    .C(_012_),
    .CE(_003_),
    .D(_009_[2]),
    .Q(\stimIn[1] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _080_ (
    .C(_012_),
    .CE(_003_),
    .D(_009_[3]),
    .Q(\stimIn[1] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _081_ (
    .C(_012_),
    .CE(_003_),
    .D(_009_[4]),
    .Q(\stimIn[1] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _082_ (
    .C(_012_),
    .CE(_003_),
    .D(_009_[5]),
    .Q(\stimIn[1] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _083_ (
    .C(_012_),
    .CE(_003_),
    .D(_009_[6]),
    .Q(\stimIn[1] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _084_ (
    .C(_012_),
    .CE(_003_),
    .D(_009_[7]),
    .Q(\stimIn[1] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _085_ (
    .C(_012_),
    .CE(_001_),
    .D(_007_[0]),
    .Q(_010_[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _086_ (
    .C(_012_),
    .CE(_001_),
    .D(_007_[1]),
    .Q(_010_[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _087_ (
    .C(_012_),
    .CE(_001_),
    .D(_007_[2]),
    .Q(_010_[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _088_ (
    .C(_012_),
    .CE(_001_),
    .D(_007_[3]),
    .Q(_010_[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _089_ (
    .C(_012_),
    .CE(_001_),
    .D(_007_[4]),
    .Q(_010_[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _090_ (
    .C(_012_),
    .CE(_001_),
    .D(_007_[5]),
    .Q(_010_[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _091_ (
    .C(_012_),
    .CE(_001_),
    .D(_007_[6]),
    .Q(_010_[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _092_ (
    .C(_012_),
    .CE(_001_),
    .D(_007_[7]),
    .Q(_010_[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _093_ (
    .C(_012_),
    .CE(_000_),
    .D(Xout[0]),
    .Q(\vectOut[0] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _094_ (
    .C(_012_),
    .CE(_000_),
    .D(Xout[1]),
    .Q(\vectOut[0] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _095_ (
    .C(_012_),
    .CE(_000_),
    .D(Xout[2]),
    .Q(\vectOut[0] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _096_ (
    .C(_012_),
    .CE(_000_),
    .D(Xout[3]),
    .Q(\vectOut[0] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _097_ (
    .C(_012_),
    .CE(_000_),
    .D(Xout[4]),
    .Q(\vectOut[0] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _098_ (
    .C(_012_),
    .CE(_000_),
    .D(Xout[5]),
    .Q(\vectOut[0] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _099_ (
    .C(_012_),
    .CE(_000_),
    .D(Xout[6]),
    .Q(\vectOut[0] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _100_ (
    .C(_012_),
    .CE(_000_),
    .D(Xout[7]),
    .Q(\vectOut[0] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _101_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[0]),
    .Q(\vectOut[1] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _102_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[1]),
    .Q(\vectOut[1] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _103_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[2]),
    .Q(\vectOut[1] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _104_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[3]),
    .Q(\vectOut[1] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _105_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[4]),
    .Q(\vectOut[1] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _106_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[5]),
    .Q(\vectOut[1] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _107_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[6]),
    .Q(\vectOut[1] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:28.5-47.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _108_ (
    .C(_012_),
    .CE(_000_),
    .D(Yout[7]),
    .Q(\vectOut[1] [7]),
    .R(1'h0)
  );
  (* keep = 32'd1 *)
  IBUF _109_ (
    .I(Addr_emu[0]),
    .O(_013_[2])
  );
  (* keep = 32'd1 *)
  IBUF _110_ (
    .I(Addr_emu[1]),
    .O(_013_[3])
  );
  (* keep = 32'd1 *)
  IBUF _111_ (
    .I(Addr_emu[2]),
    .O(_008_[2])
  );
  (* keep = 32'd1 *)
  IBUF _112_ (
    .I(Din_emu[0]),
    .O(_009_[0])
  );
  (* keep = 32'd1 *)
  IBUF _113_ (
    .I(Din_emu[1]),
    .O(_009_[1])
  );
  (* keep = 32'd1 *)
  IBUF _114_ (
    .I(Din_emu[2]),
    .O(_009_[2])
  );
  (* keep = 32'd1 *)
  IBUF _115_ (
    .I(Din_emu[3]),
    .O(_009_[3])
  );
  (* keep = 32'd1 *)
  IBUF _116_ (
    .I(Din_emu[4]),
    .O(_009_[4])
  );
  (* keep = 32'd1 *)
  IBUF _117_ (
    .I(Din_emu[5]),
    .O(_009_[5])
  );
  (* keep = 32'd1 *)
  IBUF _118_ (
    .I(Din_emu[6]),
    .O(_009_[6])
  );
  (* keep = 32'd1 *)
  IBUF _119_ (
    .I(Din_emu[7]),
    .O(_009_[7])
  );
  (* keep = 32'd1 *)
  OBUF _120_ (
    .I(_010_[0]),
    .O(Dout_emu[0])
  );
  (* keep = 32'd1 *)
  OBUF _121_ (
    .I(_010_[1]),
    .O(Dout_emu[1])
  );
  (* keep = 32'd1 *)
  OBUF _122_ (
    .I(_010_[2]),
    .O(Dout_emu[2])
  );
  (* keep = 32'd1 *)
  OBUF _123_ (
    .I(_010_[3]),
    .O(Dout_emu[3])
  );
  (* keep = 32'd1 *)
  OBUF _124_ (
    .I(_010_[4]),
    .O(Dout_emu[4])
  );
  (* keep = 32'd1 *)
  OBUF _125_ (
    .I(_010_[5]),
    .O(Dout_emu[5])
  );
  (* keep = 32'd1 *)
  OBUF _126_ (
    .I(_010_[6]),
    .O(Dout_emu[6])
  );
  (* keep = 32'd1 *)
  OBUF _127_ (
    .I(_010_[7]),
    .O(Dout_emu[7])
  );
  (* keep = 32'd1 *)
  IBUF _128_ (
    .I(clk_dut),
    .O(_005_)
  );
  (* keep = 32'd1 *)
  IBUF _129_ (
    .I(clk_emu),
    .O(_006_)
  );
  (* keep = 32'd1 *)
  IBUF _130_ (
    .I(get_emu),
    .O(_013_[0])
  );
  (* keep = 32'd1 *)
  IBUF _131_ (
    .I(load_emu),
    .O(_013_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../fir8_wrapper.v:50.10-55.21" *)
  fir8 u_fir8 (
    .Xin(Xin),
    .Xout(Xout),
    .Yin(Yin),
    .Yout(Yout),
    .clk(_011_)
  );
  assign _008_[1:0] = _013_[3:2];
endmodule

(* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:11.1-40.10" *)
module fir_pe(clk, Cin, Xin, Xout, Yin, Yout);
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0_;
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:13.17-13.20" *)
  input [7:0] Cin;
  wire [7:0] Cin;
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:14.17-14.20" *)
  input [7:0] Xin;
  wire [7:0] Xin;
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:15.17-15.21" *)
  output [7:0] Xout;
  wire [7:0] Xout;
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:16.17-16.20" *)
  input [15:0] Yin;
  wire [15:0] Yin;
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:17.17-17.21" *)
  output [15:0] Yout;
  wire [15:0] Yout;
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:12.17-12.20" *)
  input clk;
  wire clk;
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:34.5-38.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _1_ (
    .C(clk),
    .CE(1'h1),
    .D(Xin[0]),
    .Q(Xout[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:34.5-38.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _2_ (
    .C(clk),
    .CE(1'h1),
    .D(Xin[1]),
    .Q(Xout[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:34.5-38.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _3_ (
    .C(clk),
    .CE(1'h1),
    .D(Xin[2]),
    .Q(Xout[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:34.5-38.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _4_ (
    .C(clk),
    .CE(1'h1),
    .D(Xin[3]),
    .Q(Xout[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:34.5-38.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _5_ (
    .C(clk),
    .CE(1'h1),
    .D(Xin[4]),
    .Q(Xout[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:34.5-38.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _6_ (
    .C(clk),
    .CE(1'h1),
    .D(Xin[5]),
    .Q(Xout[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:34.5-38.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _7_ (
    .C(clk),
    .CE(1'h1),
    .D(Xin[6]),
    .Q(Xout[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:34.5-38.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _8_ (
    .C(clk),
    .CE(1'h1),
    .D(Xin[7]),
    .Q(Xout[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../../2-5_Lab3_FIR8/rtl_verilog/fir_pe.v:26.16-26.25|/usr/local/bin/../share/yosys/mul2dsp.v:91.5-95.4|/usr/local/bin/../share/yosys/mul2dsp.v:253.6-257.5|/usr/local/bin/../share/yosys/xilinx/xc7_dsp_map.v:30.4-48.3" *)
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'd1),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(1'h1),
    .OPMODEREG(32'sd0),
    .PREG(1'h1),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _9_ (
    .A({ 22'h000000, Xin }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B({ 10'h000, Cin }),
    .BCIN(18'h00000),
    .C({ 32'h00000000, Yin }),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .CEC(1'h1),
    .CEM(1'h1),
    .CEP(1'h1),
    .CLK(clk),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h35),
    .P({ _0_, Yout }),
    .PCIN(48'h000000000000),
    .RSTC(1'h0),
    .RSTM(1'h0),
    .RSTP(1'h0)
  );
endmodule
