-d /home/goodkook/ETRI050_DesignKit/devel/Tutorials/7-1_Vitis-HLS_basic_loop/emulation/PSCE-TRANS/Gowin/test_wrapper/impl/gwsynthesis/test_wrapper.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst /home/goodkook/ETRI050_DesignKit/devel/Tutorials/7-1_Vitis-HLS_basic_loop/emulation/PSCE-TRANS/Gowin/test_wrapper/src/psce_wrapper.cst
-cfg /home/goodkook/ETRI050_DesignKit/devel/Tutorials/7-1_Vitis-HLS_basic_loop/emulation/PSCE-TRANS/Gowin/test_wrapper/impl/pnr/device.cfg
-sdc /home/goodkook/ETRI050_DesignKit/devel/Tutorials/7-1_Vitis-HLS_basic_loop/emulation/PSCE-TRANS/Gowin/test_wrapper/src/psce_wrapper.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
