/* Generated by Yosys 0.49+5 (git sha1 954250d1d, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "../../fir_pe_wrapper.v:6.1-68.10" *)
module fir_pe_wrapper(\Din_emu[0] , \Din_emu[1] , \Din_emu[2] , \Din_emu[3] , \Din_emu[4] , \Din_emu[5] , \Din_emu[6] , \Din_emu[7] , \Dout_emu[0] , \Dout_emu[1] , \Dout_emu[2] , \Dout_emu[3] , \Dout_emu[4] , \Dout_emu[5] , \Dout_emu[6] , \Dout_emu[7] , \Addr_emu[0] , \Addr_emu[1] , \Addr_emu[2] , load_emu, get_emu
, clk_emu, clk_dut, clk, \Cin[0] , \Cin[1] , \Cin[2] , \Cin[3] , \Cin[4] , \Cin[5] , \Cin[6] , \Xin[0] , \Xin[1] , \Xin[2] , \Xin[3] , \Xout[0] , \Xout[1] , \Xout[2] , \Xout[3] , \Yin[0] , \Yin[1] , \Yin[2] 
, \Yin[3] , \Yout[0] , \Yout[1] , \Yout[2] , \Yout[3] , Rdy, Vld);
  (* src = "../../fir_pe_wrapper.v:12.21-12.29" *)
  input \Addr_emu[0] ;
  wire \Addr_emu[0] ;
  wire \Addr_emu[0]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:12.21-12.29" *)
  input \Addr_emu[1] ;
  wire \Addr_emu[1] ;
  wire \Addr_emu[1]_IBUF_I_O ;
  wire \Addr_emu[1]_IBUF_I_O_LUT4_I0_2_F ;
  wire \Addr_emu[1]_IBUF_I_O_LUT4_I0_F ;
  (* src = "../../fir_pe_wrapper.v:12.21-12.29" *)
  input \Addr_emu[2] ;
  wire \Addr_emu[2] ;
  (* unused_bits = "0" *)
  wire \Addr_emu[2]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:17.21-17.24" *)
  output \Cin[0] ;
  wire \Cin[0] ;
  wire \Cin[0]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:17.21-17.24" *)
  output \Cin[1] ;
  wire \Cin[1] ;
  wire \Cin[1]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:17.21-17.24" *)
  output \Cin[2] ;
  wire \Cin[2] ;
  wire \Cin[2]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:17.21-17.24" *)
  output \Cin[3] ;
  wire \Cin[3] ;
  wire \Cin[3]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:17.21-17.24" *)
  output \Cin[4] ;
  wire \Cin[4] ;
  wire \Cin[4]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:17.21-17.24" *)
  output \Cin[5] ;
  wire \Cin[5] ;
  wire \Cin[5]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:17.21-17.24" *)
  output \Cin[6] ;
  wire \Cin[6] ;
  wire \Cin[6]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:10.21-10.28" *)
  input \Din_emu[0] ;
  wire \Din_emu[0] ;
  wire \Din_emu[0]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:10.21-10.28" *)
  input \Din_emu[1] ;
  wire \Din_emu[1] ;
  wire \Din_emu[1]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:10.21-10.28" *)
  input \Din_emu[2] ;
  wire \Din_emu[2] ;
  wire \Din_emu[2]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:10.21-10.28" *)
  input \Din_emu[3] ;
  wire \Din_emu[3] ;
  wire \Din_emu[3]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:10.21-10.28" *)
  input \Din_emu[4] ;
  wire \Din_emu[4] ;
  wire \Din_emu[4]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:10.21-10.28" *)
  input \Din_emu[5] ;
  wire \Din_emu[5] ;
  wire \Din_emu[5]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:10.21-10.28" *)
  input \Din_emu[6] ;
  wire \Din_emu[6] ;
  wire \Din_emu[6]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:10.21-10.28" *)
  input \Din_emu[7] ;
  wire \Din_emu[7] ;
  (* src = "../../fir_pe_wrapper.v:11.21-11.29" *)
  output \Dout_emu[0] ;
  wire \Dout_emu[0] ;
  wire \Dout_emu[0]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:11.21-11.29" *)
  output \Dout_emu[1] ;
  wire \Dout_emu[1] ;
  wire \Dout_emu[1]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:11.21-11.29" *)
  output \Dout_emu[2] ;
  wire \Dout_emu[2] ;
  wire \Dout_emu[2]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:11.21-11.29" *)
  output \Dout_emu[3] ;
  wire \Dout_emu[3] ;
  wire \Dout_emu[3]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:11.21-11.29" *)
  output \Dout_emu[4] ;
  wire \Dout_emu[4] ;
  wire \Dout_emu[4]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:11.21-11.29" *)
  output \Dout_emu[5] ;
  wire \Dout_emu[5] ;
  wire \Dout_emu[5]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:11.21-11.29" *)
  output \Dout_emu[6] ;
  wire \Dout_emu[6] ;
  wire \Dout_emu[6]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:11.21-11.29" *)
  output \Dout_emu[7] ;
  wire \Dout_emu[7] ;
  wire \Dout_emu[7]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:22.21-22.24" *)
  output Rdy;
  wire Rdy;
  wire Rdy_OBUF_O_I;
  (* src = "../../fir_pe_wrapper.v:23.21-23.24" *)
  input Vld;
  wire Vld;
  (* src = "../../fir_pe_wrapper.v:18.21-18.24" *)
  output \Xin[0] ;
  wire \Xin[0] ;
  wire \Xin[0]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:18.21-18.24" *)
  output \Xin[1] ;
  wire \Xin[1] ;
  wire \Xin[1]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:18.21-18.24" *)
  output \Xin[2] ;
  wire \Xin[2] ;
  wire \Xin[2]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:18.21-18.24" *)
  output \Xin[3] ;
  wire \Xin[3] ;
  wire \Xin[3]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:19.21-19.25" *)
  input \Xout[0] ;
  wire \Xout[0] ;
  wire \Xout[0]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:19.21-19.25" *)
  input \Xout[1] ;
  wire \Xout[1] ;
  wire \Xout[1]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:19.21-19.25" *)
  input \Xout[2] ;
  wire \Xout[2] ;
  wire \Xout[2]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:19.21-19.25" *)
  input \Xout[3] ;
  wire \Xout[3] ;
  wire \Xout[3]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:20.21-20.24" *)
  output \Yin[0] ;
  wire \Yin[0] ;
  wire \Yin[0]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:20.21-20.24" *)
  output \Yin[1] ;
  wire \Yin[1] ;
  wire \Yin[1]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:20.21-20.24" *)
  output \Yin[2] ;
  wire \Yin[2] ;
  wire \Yin[2]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:20.21-20.24" *)
  output \Yin[3] ;
  wire \Yin[3] ;
  wire \Yin[3]_OBUF_O_I ;
  (* src = "../../fir_pe_wrapper.v:21.21-21.25" *)
  input \Yout[0] ;
  wire \Yout[0] ;
  wire \Yout[0]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:21.21-21.25" *)
  input \Yout[1] ;
  wire \Yout[1] ;
  wire \Yout[1]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:21.21-21.25" *)
  input \Yout[2] ;
  wire \Yout[2] ;
  wire \Yout[2]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:21.21-21.25" *)
  input \Yout[3] ;
  wire \Yout[3] ;
  wire \Yout[3]_IBUF_I_O ;
  (* src = "../../fir_pe_wrapper.v:16.21-16.24" *)
  output clk;
  wire clk;
  wire clk_OBUF_O_I;
  (* src = "../../fir_pe_wrapper.v:14.21-14.28" *)
  input clk_dut;
  wire clk_dut;
  (* src = "../../fir_pe_wrapper.v:13.40-13.47" *)
  input clk_emu;
  wire clk_emu;
  wire clk_emu_IBUF_I_O;
  (* src = "../../fir_pe_wrapper.v:13.31-13.38" *)
  input get_emu;
  wire get_emu;
  wire get_emu_IBUF_I_O;
  (* src = "../../fir_pe_wrapper.v:13.21-13.29" *)
  input load_emu;
  wire load_emu;
  wire load_emu_IBUF_I_O;
  wire \stimIn[0][0] ;
  wire \stimIn[0][1] ;
  wire \stimIn[0][2] ;
  wire \stimIn[0][3] ;
  wire \stimIn[0][4] ;
  wire \stimIn[0][5] ;
  wire \stimIn[0][6] ;
  (* unused_bits = "0" *)
  wire \stimIn[0][7] ;
  wire \stimIn[1][0] ;
  wire \stimIn[1][1] ;
  wire \stimIn[1][2] ;
  wire \stimIn[1][3] ;
  wire \stimIn[1][4] ;
  wire \stimIn[1][5] ;
  wire \stimIn[1][6] ;
  wire \stimIn[1][7] ;
  wire \stimIn[1][7]_DFFE_Q_D ;
  wire \stimIn[2][0] ;
  wire \stimIn[2][0]_DFFE_Q_CE ;
  (* unused_bits = "0" *)
  wire \stimIn[2][1] ;
  (* unused_bits = "0" *)
  wire \stimIn[2][2] ;
  (* unused_bits = "0" *)
  wire \stimIn[2][3] ;
  (* unused_bits = "0" *)
  wire \stimIn[2][4] ;
  (* unused_bits = "0" *)
  wire \stimIn[2][5] ;
  (* unused_bits = "0" *)
  wire \stimIn[2][6] ;
  (* unused_bits = "0" *)
  wire \stimIn[2][7] ;
  (* src = "../../fir_pe_wrapper.v:29.17-29.24" *)
  wire \vectOut[0][0] ;
  (* src = "../../fir_pe_wrapper.v:29.17-29.24" *)
  wire \vectOut[0][1] ;
  wire \vectOut[0][1]_DFFRE_D_CE ;
  wire \vectOut[0][1]_DFFRE_D_RESET ;
  (* src = "../../fir_pe_wrapper.v:29.17-29.24" *)
  wire \vectOut[0][2] ;
  (* src = "../../fir_pe_wrapper.v:29.17-29.24" *)
  wire \vectOut[0][3] ;
  (* src = "../../fir_pe_wrapper.v:29.17-29.24" *)
  wire \vectOut[0][4] ;
  (* src = "../../fir_pe_wrapper.v:29.17-29.24" *)
  wire \vectOut[0][5] ;
  (* src = "../../fir_pe_wrapper.v:29.17-29.24" *)
  wire \vectOut[0][6] ;
  (* src = "../../fir_pe_wrapper.v:29.17-29.24" *)
  wire \vectOut[0][7] ;
  wire \vectOut[1] ;
  wire \vectOut[1]_DFFE_Q_CE ;
  wire \vectOut[1]_DFFE_Q_D ;
  wire \vectOut[1]_LUT3_I1_F ;
  (* keep = 32'd1 *)
  IBUF \Addr_emu[0]_IBUF_I  (
    .I(\Addr_emu[0] ),
    .O(\Addr_emu[0]_IBUF_I_O )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h04)
  ) \Addr_emu[0]_IBUF_I_O_LUT3_I1  (
    .F(\vectOut[0][1]_DFFRE_D_RESET ),
    .I0(load_emu_IBUF_I_O),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(get_emu_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  IBUF \Addr_emu[1]_IBUF_I  (
    .I(\Addr_emu[1] ),
    .O(\Addr_emu[1]_IBUF_I_O )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h0010)
  ) \Addr_emu[1]_IBUF_I_O_LUT4_I0  (
    .F(\Addr_emu[1]_IBUF_I_O_LUT4_I0_F ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(load_emu_IBUF_I_O),
    .I2(\Addr_emu[0]_IBUF_I_O ),
    .I3(get_emu_IBUF_I_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h0002)
  ) \Addr_emu[1]_IBUF_I_O_LUT4_I0_1  (
    .F(\stimIn[2][0]_DFFE_Q_CE ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(load_emu_IBUF_I_O),
    .I2(\Addr_emu[0]_IBUF_I_O ),
    .I3(get_emu_IBUF_I_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h0001)
  ) \Addr_emu[1]_IBUF_I_O_LUT4_I0_2  (
    .F(\Addr_emu[1]_IBUF_I_O_LUT4_I0_2_F ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(load_emu_IBUF_I_O),
    .I2(\Addr_emu[0]_IBUF_I_O ),
    .I3(get_emu_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  IBUF \Addr_emu[2]_IBUF_I  (
    .I(\Addr_emu[2] ),
    .O(\Addr_emu[2]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  OBUF \Cin[0]_OBUF_O  (
    .I(\Cin[0]_OBUF_O_I ),
    .O(\Cin[0] )
  );
  (* keep = 32'd1 *)
  OBUF \Cin[1]_OBUF_O  (
    .I(\Cin[1]_OBUF_O_I ),
    .O(\Cin[1] )
  );
  (* keep = 32'd1 *)
  OBUF \Cin[2]_OBUF_O  (
    .I(\Cin[2]_OBUF_O_I ),
    .O(\Cin[2] )
  );
  (* keep = 32'd1 *)
  OBUF \Cin[3]_OBUF_O  (
    .I(\Cin[3]_OBUF_O_I ),
    .O(\Cin[3] )
  );
  (* keep = 32'd1 *)
  OBUF \Cin[4]_OBUF_O  (
    .I(\Cin[4]_OBUF_O_I ),
    .O(\Cin[4] )
  );
  (* keep = 32'd1 *)
  OBUF \Cin[5]_OBUF_O  (
    .I(\Cin[5]_OBUF_O_I ),
    .O(\Cin[5] )
  );
  (* keep = 32'd1 *)
  OBUF \Cin[6]_OBUF_O  (
    .I(\Cin[6]_OBUF_O_I ),
    .O(\Cin[6] )
  );
  (* keep = 32'd1 *)
  IBUF \Din_emu[0]_IBUF_I  (
    .I(\Din_emu[0] ),
    .O(\Din_emu[0]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Din_emu[1]_IBUF_I  (
    .I(\Din_emu[1] ),
    .O(\Din_emu[1]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Din_emu[2]_IBUF_I  (
    .I(\Din_emu[2] ),
    .O(\Din_emu[2]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Din_emu[3]_IBUF_I  (
    .I(\Din_emu[3] ),
    .O(\Din_emu[3]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Din_emu[4]_IBUF_I  (
    .I(\Din_emu[4] ),
    .O(\Din_emu[4]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Din_emu[5]_IBUF_I  (
    .I(\Din_emu[5] ),
    .O(\Din_emu[5]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Din_emu[6]_IBUF_I  (
    .I(\Din_emu[6] ),
    .O(\Din_emu[6]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Din_emu[7]_IBUF_I  (
    .I(\Din_emu[7] ),
    .O(\stimIn[1][7]_DFFE_Q_D )
  );
  (* keep = 32'd1 *)
  OBUF \Dout_emu[0]_OBUF_O  (
    .I(\Dout_emu[0]_OBUF_O_I ),
    .O(\Dout_emu[0] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \Dout_emu[0]_OBUF_O_I_DFFE_Q  (
    .CE(\vectOut[0][1]_DFFRE_D_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1]_LUT3_I1_F ),
    .Q(\Dout_emu[0]_OBUF_O_I )
  );
  (* keep = 32'd1 *)
  OBUF \Dout_emu[1]_OBUF_O  (
    .I(\Dout_emu[1]_OBUF_O_I ),
    .O(\Dout_emu[1] )
  );
  (* keep = 32'd1 *)
  OBUF \Dout_emu[2]_OBUF_O  (
    .I(\Dout_emu[2]_OBUF_O_I ),
    .O(\Dout_emu[2] )
  );
  (* keep = 32'd1 *)
  OBUF \Dout_emu[3]_OBUF_O  (
    .I(\Dout_emu[3]_OBUF_O_I ),
    .O(\Dout_emu[3] )
  );
  (* keep = 32'd1 *)
  OBUF \Dout_emu[4]_OBUF_O  (
    .I(\Dout_emu[4]_OBUF_O_I ),
    .O(\Dout_emu[4] )
  );
  (* keep = 32'd1 *)
  OBUF \Dout_emu[5]_OBUF_O  (
    .I(\Dout_emu[5]_OBUF_O_I ),
    .O(\Dout_emu[5] )
  );
  (* keep = 32'd1 *)
  OBUF \Dout_emu[6]_OBUF_O  (
    .I(\Dout_emu[6]_OBUF_O_I ),
    .O(\Dout_emu[6] )
  );
  (* keep = 32'd1 *)
  OBUF \Dout_emu[7]_OBUF_O  (
    .I(\Dout_emu[7]_OBUF_O_I ),
    .O(\Dout_emu[7] )
  );
  (* keep = 32'd1 *)
  OBUF Rdy_OBUF_O (
    .I(Rdy_OBUF_O_I),
    .O(Rdy)
  );
  (* keep = 32'd1 *)
  IBUF Vld_IBUF_I (
    .I(Vld),
    .O(\vectOut[1]_DFFE_Q_D )
  );
  (* keep = 32'd1 *)
  OBUF \Xin[0]_OBUF_O  (
    .I(\Xin[0]_OBUF_O_I ),
    .O(\Xin[0] )
  );
  (* keep = 32'd1 *)
  OBUF \Xin[1]_OBUF_O  (
    .I(\Xin[1]_OBUF_O_I ),
    .O(\Xin[1] )
  );
  (* keep = 32'd1 *)
  OBUF \Xin[2]_OBUF_O  (
    .I(\Xin[2]_OBUF_O_I ),
    .O(\Xin[2] )
  );
  (* keep = 32'd1 *)
  OBUF \Xin[3]_OBUF_O  (
    .I(\Xin[3]_OBUF_O_I ),
    .O(\Xin[3] )
  );
  (* keep = 32'd1 *)
  IBUF \Xout[0]_IBUF_I  (
    .I(\Xout[0] ),
    .O(\Xout[0]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Xout[1]_IBUF_I  (
    .I(\Xout[1] ),
    .O(\Xout[1]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Xout[2]_IBUF_I  (
    .I(\Xout[2] ),
    .O(\Xout[2]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Xout[3]_IBUF_I  (
    .I(\Xout[3] ),
    .O(\Xout[3]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  OBUF \Yin[0]_OBUF_O  (
    .I(\Yin[0]_OBUF_O_I ),
    .O(\Yin[0] )
  );
  (* keep = 32'd1 *)
  OBUF \Yin[1]_OBUF_O  (
    .I(\Yin[1]_OBUF_O_I ),
    .O(\Yin[1] )
  );
  (* keep = 32'd1 *)
  OBUF \Yin[2]_OBUF_O  (
    .I(\Yin[2]_OBUF_O_I ),
    .O(\Yin[2] )
  );
  (* keep = 32'd1 *)
  OBUF \Yin[3]_OBUF_O  (
    .I(\Yin[3]_OBUF_O_I ),
    .O(\Yin[3] )
  );
  (* keep = 32'd1 *)
  IBUF \Yout[0]_IBUF_I  (
    .I(\Yout[0] ),
    .O(\Yout[0]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Yout[1]_IBUF_I  (
    .I(\Yout[1] ),
    .O(\Yout[1]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Yout[2]_IBUF_I  (
    .I(\Yout[2] ),
    .O(\Yout[2]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  IBUF \Yout[3]_IBUF_I  (
    .I(\Yout[3] ),
    .O(\Yout[3]_IBUF_I_O )
  );
  (* keep = 32'd1 *)
  OBUF clk_OBUF_O (
    .I(clk_OBUF_O_I),
    .O(clk)
  );
  (* keep = 32'd1 *)
  IBUF clk_dut_IBUF_I (
    .I(clk_dut),
    .O(clk_OBUF_O_I)
  );
  (* keep = 32'd1 *)
  IBUF clk_emu_IBUF_I (
    .I(clk_emu),
    .O(clk_emu_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  IBUF get_emu_IBUF_I (
    .I(get_emu),
    .O(get_emu_IBUF_I_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:139.23-140.26" *)
  LUT2 #(
    .INIT(4'h1)
  ) get_emu_IBUF_I_O_LUT2_I1 (
    .F(\vectOut[0][1]_DFFRE_D_CE ),
    .I0(load_emu_IBUF_I_O),
    .I1(get_emu_IBUF_I_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:139.23-140.26" *)
  LUT2 #(
    .INIT(4'h4)
  ) get_emu_IBUF_I_O_LUT2_I1_1 (
    .F(\vectOut[1]_DFFE_Q_CE ),
    .I0(load_emu_IBUF_I_O),
    .I1(get_emu_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  IBUF load_emu_IBUF_I (
    .I(load_emu),
    .O(load_emu_IBUF_I_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][0]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][0] ),
    .Q(\Cin[0]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][0]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_2_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[0]_IBUF_I_O ),
    .Q(\stimIn[0][0] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][1]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][1] ),
    .Q(\Cin[1]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][1]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_2_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[1]_IBUF_I_O ),
    .Q(\stimIn[0][1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][2]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][2] ),
    .Q(\Cin[2]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][2]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_2_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[2]_IBUF_I_O ),
    .Q(\stimIn[0][2] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][3]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][3] ),
    .Q(\Cin[3]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][3]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_2_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[3]_IBUF_I_O ),
    .Q(\stimIn[0][3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][4]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][4] ),
    .Q(\Cin[4]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][4]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_2_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[4]_IBUF_I_O ),
    .Q(\stimIn[0][4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][5]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][5] ),
    .Q(\Cin[5]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][5]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_2_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[5]_IBUF_I_O ),
    .Q(\stimIn[0][5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][6]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][6] ),
    .Q(\Cin[6]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[0][6]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_2_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[6]_IBUF_I_O ),
    .Q(\stimIn[0][6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][0]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[1][0] ),
    .Q(\Xin[0]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][0]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[0]_IBUF_I_O ),
    .Q(\stimIn[1][0] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][1]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[1][1] ),
    .Q(\Xin[1]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][1]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[1]_IBUF_I_O ),
    .Q(\stimIn[1][1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][2]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[1][2] ),
    .Q(\Xin[2]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][2]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[2]_IBUF_I_O ),
    .Q(\stimIn[1][2] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][3]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[1][3] ),
    .Q(\Xin[3]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][3]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[3]_IBUF_I_O ),
    .Q(\stimIn[1][3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][4]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[1][4] ),
    .Q(\Yin[0]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][4]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[4]_IBUF_I_O ),
    .Q(\stimIn[1][4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][5]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[1][5] ),
    .Q(\Yin[1]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][5]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[5]_IBUF_I_O ),
    .Q(\stimIn[1][5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][6]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[1][6] ),
    .Q(\Yin[2]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][6]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[6]_IBUF_I_O ),
    .Q(\stimIn[1][6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][7]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[1][7] ),
    .Q(\Yin[3]_OBUF_O_I )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[1][7]_DFFE_Q  (
    .CE(\Addr_emu[1]_IBUF_I_O_LUT4_I0_F ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[1][7]_DFFE_Q_D ),
    .Q(\stimIn[1][7] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[2][0]_DFFE_D  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[2][0] ),
    .Q(Rdy_OBUF_O_I)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \stimIn[2][0]_DFFE_Q  (
    .CE(\stimIn[2][0]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din_emu[0]_IBUF_I_O ),
    .Q(\stimIn[2][0] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \vectOut[0][0]_DFFE_Q  (
    .CE(\vectOut[1]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Xout[0]_IBUF_I_O ),
    .Q(\vectOut[0][0] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \vectOut[0][1]_DFFE_Q  (
    .CE(\vectOut[1]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Xout[1]_IBUF_I_O ),
    .Q(\vectOut[0][1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:43.8-43.68" *)
  DFFRE \vectOut[0][1]_DFFRE_D  (
    .CE(\vectOut[0][1]_DFFRE_D_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][1] ),
    .Q(\Dout_emu[1]_OBUF_O_I ),
    .RESET(\vectOut[0][1]_DFFRE_D_RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \vectOut[0][2]_DFFE_Q  (
    .CE(\vectOut[1]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Xout[2]_IBUF_I_O ),
    .Q(\vectOut[0][2] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:43.8-43.68" *)
  DFFRE \vectOut[0][2]_DFFRE_D  (
    .CE(\vectOut[0][1]_DFFRE_D_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][2] ),
    .Q(\Dout_emu[2]_OBUF_O_I ),
    .RESET(\vectOut[0][1]_DFFRE_D_RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \vectOut[0][3]_DFFE_Q  (
    .CE(\vectOut[1]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Xout[3]_IBUF_I_O ),
    .Q(\vectOut[0][3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:43.8-43.68" *)
  DFFRE \vectOut[0][3]_DFFRE_D  (
    .CE(\vectOut[0][1]_DFFRE_D_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][3] ),
    .Q(\Dout_emu[3]_OBUF_O_I ),
    .RESET(\vectOut[0][1]_DFFRE_D_RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \vectOut[0][4]_DFFE_Q  (
    .CE(\vectOut[1]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Yout[0]_IBUF_I_O ),
    .Q(\vectOut[0][4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:43.8-43.68" *)
  DFFRE \vectOut[0][4]_DFFRE_D  (
    .CE(\vectOut[0][1]_DFFRE_D_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][4] ),
    .Q(\Dout_emu[4]_OBUF_O_I ),
    .RESET(\vectOut[0][1]_DFFRE_D_RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \vectOut[0][5]_DFFE_Q  (
    .CE(\vectOut[1]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Yout[1]_IBUF_I_O ),
    .Q(\vectOut[0][5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:43.8-43.68" *)
  DFFRE \vectOut[0][5]_DFFRE_D  (
    .CE(\vectOut[0][1]_DFFRE_D_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][5] ),
    .Q(\Dout_emu[5]_OBUF_O_I ),
    .RESET(\vectOut[0][1]_DFFRE_D_RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \vectOut[0][6]_DFFE_Q  (
    .CE(\vectOut[1]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Yout[2]_IBUF_I_O ),
    .Q(\vectOut[0][6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:43.8-43.68" *)
  DFFRE \vectOut[0][6]_DFFRE_D  (
    .CE(\vectOut[0][1]_DFFRE_D_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][6] ),
    .Q(\Dout_emu[6]_OBUF_O_I ),
    .RESET(\vectOut[0][1]_DFFRE_D_RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \vectOut[0][7]_DFFE_Q  (
    .CE(\vectOut[1]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Yout[3]_IBUF_I_O ),
    .Q(\vectOut[0][7] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:43.8-43.68" *)
  DFFRE \vectOut[0][7]_DFFRE_D  (
    .CE(\vectOut[0][1]_DFFRE_D_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][7] ),
    .Q(\Dout_emu[7]_OBUF_O_I ),
    .RESET(\vectOut[0][1]_DFFRE_D_RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:43.5-64.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \vectOut[1]_DFFE_Q  (
    .CE(\vectOut[1]_DFFE_Q_CE ),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1]_DFFE_Q_D ),
    .Q(\vectOut[1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'hd8)
  ) \vectOut[1]_LUT3_I1  (
    .F(\vectOut[1]_LUT3_I1_F ),
    .I0(\Addr_emu[0]_IBUF_I_O ),
    .I1(\vectOut[1] ),
    .I2(\vectOut[0][0] )
  );
  assign \stimIn[2][2]  = \stimIn[0][7] ;
  assign \stimIn[2][3]  = \stimIn[0][7] ;
  assign \stimIn[2][4]  = \stimIn[0][7] ;
  assign \stimIn[2][5]  = \stimIn[0][7] ;
  assign \stimIn[2][6]  = \stimIn[0][7] ;
  assign \stimIn[2][7]  = \stimIn[0][7] ;
  assign \stimIn[2][1]  = \stimIn[0][7] ;
endmodule
