#!/usr/bin/bash

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/bin
export PATH=/opt/intelFPGA_standard/24.1std/quartus/bin:$PATH
export LM_LICENSE_FILE=/home/goodkook/.altera.quartus/quartus2_lic.dat

