/* Generated by Yosys 0.41+111 (git sha1 4b67f3757, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "../../fir_pe_wrapper.v:7.1-73.10" *)
module fir_pe_wrapper(Din_emu, Dout_emu, Addr_emu, load_emu, get_emu, clk_emu, clk_dut, clk_LED);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  (* force_downto = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:22.20-22.31|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:22.20-22.31|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [3:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:22.20-22.31|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [3:0] _008_;
  wire _009_;
  wire _010_;
  (* force_downto = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:137.23-137.24" *)
  wire [7:0] _011_;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _012_;
  (* unused_bits = "2" *)
  wire [2:0] _013_;
  wire [7:0] _014_;
  wire [7:0] _015_;
  wire _016_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _017_;
  (* src = "../../fir_pe_wrapper.v:13.21-13.29" *)
  input [2:0] Addr_emu;
  wire [2:0] Addr_emu;
  (* src = "../../fir_pe_wrapper.v:34.17-34.20" *)
  wire [7:0] Cin;
  (* src = "../../fir_pe_wrapper.v:11.21-11.28" *)
  input [7:0] Din_emu;
  wire [7:0] Din_emu;
  (* src = "../../fir_pe_wrapper.v:12.21-12.29" *)
  output [7:0] Dout_emu;
  wire [7:0] Dout_emu;
  (* src = "../../fir_pe_wrapper.v:35.17-35.20" *)
  wire [7:0] Xin;
  (* src = "../../fir_pe_wrapper.v:38.17-38.21" *)
  wire [7:0] Xout;
  (* src = "../../fir_pe_wrapper.v:36.17-36.20" *)
  wire [15:0] Yin;
  (* src = "../../fir_pe_wrapper.v:39.17-39.21" *)
  wire [15:0] Yout;
  (* src = "../../fir_pe_wrapper.v:17.12-17.19" *)
  output clk_LED;
  wire clk_LED;
  (* src = "../../fir_pe_wrapper.v:15.21-15.28" *)
  input clk_dut;
  wire clk_dut;
  (* src = "../../fir_pe_wrapper.v:14.40-14.47" *)
  input clk_emu;
  wire clk_emu;
  (* src = "../../fir_pe_wrapper.v:19.15-19.22" *)
  wire [3:0] counter;
  (* src = "../../fir_pe_wrapper.v:14.31-14.38" *)
  input get_emu;
  wire get_emu;
  (* src = "../../fir_pe_wrapper.v:14.21-14.29" *)
  input load_emu;
  wire load_emu;
  wire [7:0] \stimIn[0] ;
  wire [7:0] \stimIn[1] ;
  wire [7:0] \stimIn[2] ;
  wire [7:0] \stimIn[3] ;
  (* hdlname = "u_fir_pe Cin" *)
  (* src = "../../../source/fir_pe.v:13.17-13.20" *)
  wire [7:0] \u_fir_pe.Cin ;
  (* hdlname = "u_fir_pe Xin" *)
  (* src = "../../../source/fir_pe.v:14.17-14.20" *)
  wire [7:0] \u_fir_pe.Xin ;
  (* hdlname = "u_fir_pe Xout" *)
  (* src = "../../../source/fir_pe.v:15.17-15.21" *)
  wire [7:0] \u_fir_pe.Xout ;
  (* hdlname = "u_fir_pe Yin" *)
  (* src = "../../../source/fir_pe.v:16.17-16.20" *)
  wire [15:0] \u_fir_pe.Yin ;
  (* hdlname = "u_fir_pe Yout" *)
  (* src = "../../../source/fir_pe.v:17.17-17.21" *)
  wire [15:0] \u_fir_pe.Yout ;
  (* hdlname = "u_fir_pe clk" *)
  (* src = "../../../source/fir_pe.v:12.17-12.20" *)
  wire \u_fir_pe.clk ;
  (* hdlname = "u_fir_pe y" *)
  (* src = "../../../source/fir_pe.v:21.21-21.22" *)
  wire [15:0] \u_fir_pe.y ;
  (* src = "../../fir_pe_wrapper.v:30.17-30.24" *)
  wire [7:0] \vectOut[0] ;
  (* src = "../../fir_pe_wrapper.v:30.17-30.24" *)
  wire [7:0] \vectOut[1] ;
  (* src = "../../fir_pe_wrapper.v:30.17-30.24" *)
  wire [7:0] \vectOut[2] ;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _018_ (
    .I0(_017_[1]),
    .I1(_017_[0]),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _019_ (
    .I0(_017_[0]),
    .I1(_017_[1]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042304204)
  ) _020_ (
    .I0(\vectOut[1] [0]),
    .I1(\vectOut[0] [0]),
    .I2(\vectOut[2] [0]),
    .I3(_017_[3]),
    .I4(_017_[2]),
    .O(_011_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _021_ (
    .I0(\vectOut[0] [1]),
    .I1(\vectOut[1] [1]),
    .I2(\vectOut[2] [1]),
    .I3(_017_[3]),
    .I4(_017_[2]),
    .O(_011_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _022_ (
    .I0(\vectOut[0] [2]),
    .I1(\vectOut[1] [2]),
    .I2(\vectOut[2] [2]),
    .I3(_017_[3]),
    .I4(_017_[2]),
    .O(_011_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _023_ (
    .I0(\vectOut[0] [3]),
    .I1(\vectOut[1] [3]),
    .I2(\vectOut[2] [3]),
    .I3(_017_[3]),
    .I4(_017_[2]),
    .O(_011_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _024_ (
    .I0(\vectOut[0] [4]),
    .I1(\vectOut[1] [4]),
    .I2(\vectOut[2] [4]),
    .I3(_017_[3]),
    .I4(_017_[2]),
    .O(_011_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _025_ (
    .I0(\vectOut[0] [5]),
    .I1(\vectOut[1] [5]),
    .I2(\vectOut[2] [5]),
    .I3(_017_[3]),
    .I4(_017_[2]),
    .O(_011_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _026_ (
    .I0(\vectOut[0] [6]),
    .I1(\vectOut[1] [6]),
    .I2(\vectOut[2] [6]),
    .I3(_017_[3]),
    .I4(_017_[2]),
    .O(_011_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _027_ (
    .I0(\vectOut[0] [7]),
    .I1(\vectOut[1] [7]),
    .I2(\vectOut[2] [7]),
    .I3(_017_[3]),
    .I4(_017_[2]),
    .O(_011_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0001)
  ) _028_ (
    .I0(_017_[0]),
    .I1(_017_[1]),
    .I2(_017_[3]),
    .I3(_017_[2]),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _029_ (
    .I0(_017_[0]),
    .I1(_017_[1]),
    .I2(_017_[2]),
    .I3(_017_[3]),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _030_ (
    .I0(_017_[0]),
    .I1(_017_[1]),
    .I2(_017_[3]),
    .I3(_017_[2]),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h1000)
  ) _031_ (
    .I0(_017_[0]),
    .I1(_017_[1]),
    .I2(_017_[3]),
    .I3(_017_[2]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _032_ (
    .I(counter[0]),
    .O(_007_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:22.20-22.31|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _033_ (
    .CI(1'h0),
    .CO(_006_),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_008_),
    .S({ counter[3:1], _007_[0] })
  );
  BUFG _034_ (
    .I(_009_),
    .O(_016_)
  );
  BUFG _035_ (
    .I(_010_),
    .O(\u_fir_pe.clk )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _036_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[0] [7]),
    .Q(Cin[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _037_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[1] [0]),
    .Q(Xin[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _038_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[1] [1]),
    .Q(Xin[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _039_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[1] [2]),
    .Q(Xin[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _040_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[1] [3]),
    .Q(Xin[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _041_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[1] [4]),
    .Q(Xin[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _042_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[1] [5]),
    .Q(Xin[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _043_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[1] [6]),
    .Q(Xin[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _044_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[1] [7]),
    .Q(Xin[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _045_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[2] [0]),
    .Q(Yin[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _046_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[2] [1]),
    .Q(Yin[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _047_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[2] [2]),
    .Q(Yin[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _048_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[2] [3]),
    .Q(Yin[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _049_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[2] [4]),
    .Q(Yin[12]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _050_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[2] [5]),
    .Q(Yin[13]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _051_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[2] [6]),
    .Q(Yin[14]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _052_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[2] [7]),
    .Q(Yin[15]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _053_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[3] [0]),
    .Q(Yin[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _054_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[3] [1]),
    .Q(Yin[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _055_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[3] [2]),
    .Q(Yin[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _056_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[3] [3]),
    .Q(Yin[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _057_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[3] [4]),
    .Q(Yin[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _058_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[3] [5]),
    .Q(Yin[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _059_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[3] [6]),
    .Q(Yin[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _060_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[3] [7]),
    .Q(Yin[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _061_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[0] [0]),
    .Q(Cin[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _062_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[0] [1]),
    .Q(Cin[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _063_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[0] [2]),
    .Q(Cin[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _064_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[0] [3]),
    .Q(Cin[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _065_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[0] [4]),
    .Q(Cin[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _066_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[0] [5]),
    .Q(Cin[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _067_ (
    .C(_016_),
    .CE(_017_[1]),
    .D(\stimIn[0] [6]),
    .Q(Cin[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _068_ (
    .C(_016_),
    .CE(_002_),
    .D(_014_[0]),
    .Q(\stimIn[0] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _069_ (
    .C(_016_),
    .CE(_002_),
    .D(_014_[1]),
    .Q(\stimIn[0] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _070_ (
    .C(_016_),
    .CE(_002_),
    .D(_014_[2]),
    .Q(\stimIn[0] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _071_ (
    .C(_016_),
    .CE(_002_),
    .D(_014_[3]),
    .Q(\stimIn[0] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _072_ (
    .C(_016_),
    .CE(_002_),
    .D(_014_[4]),
    .Q(\stimIn[0] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _073_ (
    .C(_016_),
    .CE(_002_),
    .D(_014_[5]),
    .Q(\stimIn[0] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _074_ (
    .C(_016_),
    .CE(_002_),
    .D(_014_[6]),
    .Q(\stimIn[0] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _075_ (
    .C(_016_),
    .CE(_002_),
    .D(_014_[7]),
    .Q(\stimIn[0] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _076_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [0]),
    .Q(\u_fir_pe.Yout [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _077_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [1]),
    .Q(\u_fir_pe.Yout [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _078_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [2]),
    .Q(\u_fir_pe.Yout [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _079_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [3]),
    .Q(\u_fir_pe.Yout [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _080_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [4]),
    .Q(\u_fir_pe.Yout [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _081_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [5]),
    .Q(\u_fir_pe.Yout [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _082_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [6]),
    .Q(\u_fir_pe.Yout [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _083_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [7]),
    .Q(\u_fir_pe.Yout [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _084_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [8]),
    .Q(\u_fir_pe.Yout [8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _085_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [9]),
    .Q(\u_fir_pe.Yout [9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _086_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [10]),
    .Q(\u_fir_pe.Yout [10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _087_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [11]),
    .Q(\u_fir_pe.Yout [11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _088_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [12]),
    .Q(\u_fir_pe.Yout [12]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _089_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [13]),
    .Q(\u_fir_pe.Yout [13]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _090_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [14]),
    .Q(\u_fir_pe.Yout [14]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _091_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(\u_fir_pe.y [15]),
    .Q(\u_fir_pe.Yout [15]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _092_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(Xin[0]),
    .Q(\u_fir_pe.Xout [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _093_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(Xin[1]),
    .Q(\u_fir_pe.Xout [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _094_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(Xin[2]),
    .Q(\u_fir_pe.Xout [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _095_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(Xin[3]),
    .Q(\u_fir_pe.Xout [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _096_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(Xin[4]),
    .Q(\u_fir_pe.Xout [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _097_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(Xin[5]),
    .Q(\u_fir_pe.Xout [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _098_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(Xin[6]),
    .Q(\u_fir_pe.Xout [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:32.5-42.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _099_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(Xin[7]),
    .Q(\u_fir_pe.Xout [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _100_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [0]),
    .Q(\vectOut[2] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _101_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [1]),
    .Q(\vectOut[2] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _102_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [2]),
    .Q(\vectOut[2] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _103_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [3]),
    .Q(\vectOut[2] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _104_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [4]),
    .Q(\vectOut[2] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _105_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [5]),
    .Q(\vectOut[2] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _106_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [6]),
    .Q(\vectOut[2] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _107_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [7]),
    .Q(\vectOut[2] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _108_ (
    .C(_016_),
    .CE(_004_),
    .D(_014_[0]),
    .Q(\stimIn[2] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _109_ (
    .C(_016_),
    .CE(_004_),
    .D(_014_[1]),
    .Q(\stimIn[2] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _110_ (
    .C(_016_),
    .CE(_004_),
    .D(_014_[2]),
    .Q(\stimIn[2] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _111_ (
    .C(_016_),
    .CE(_004_),
    .D(_014_[3]),
    .Q(\stimIn[2] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _112_ (
    .C(_016_),
    .CE(_004_),
    .D(_014_[4]),
    .Q(\stimIn[2] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _113_ (
    .C(_016_),
    .CE(_004_),
    .D(_014_[5]),
    .Q(\stimIn[2] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _114_ (
    .C(_016_),
    .CE(_004_),
    .D(_014_[6]),
    .Q(\stimIn[2] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _115_ (
    .C(_016_),
    .CE(_004_),
    .D(_014_[7]),
    .Q(\stimIn[2] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _116_ (
    .C(_016_),
    .CE(_003_),
    .D(_014_[0]),
    .Q(\stimIn[1] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _117_ (
    .C(_016_),
    .CE(_003_),
    .D(_014_[1]),
    .Q(\stimIn[1] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _118_ (
    .C(_016_),
    .CE(_003_),
    .D(_014_[2]),
    .Q(\stimIn[1] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _119_ (
    .C(_016_),
    .CE(_003_),
    .D(_014_[3]),
    .Q(\stimIn[1] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _120_ (
    .C(_016_),
    .CE(_003_),
    .D(_014_[4]),
    .Q(\stimIn[1] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _121_ (
    .C(_016_),
    .CE(_003_),
    .D(_014_[5]),
    .Q(\stimIn[1] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _122_ (
    .C(_016_),
    .CE(_003_),
    .D(_014_[6]),
    .Q(\stimIn[1] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _123_ (
    .C(_016_),
    .CE(_003_),
    .D(_014_[7]),
    .Q(\stimIn[1] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _124_ (
    .C(_016_),
    .CE(_001_),
    .D(_011_[0]),
    .Q(_015_[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _125_ (
    .C(_016_),
    .CE(_001_),
    .D(_011_[1]),
    .Q(_015_[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _126_ (
    .C(_016_),
    .CE(_001_),
    .D(_011_[2]),
    .Q(_015_[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _127_ (
    .C(_016_),
    .CE(_001_),
    .D(_011_[3]),
    .Q(_015_[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _128_ (
    .C(_016_),
    .CE(_001_),
    .D(_011_[4]),
    .Q(_015_[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _129_ (
    .C(_016_),
    .CE(_001_),
    .D(_011_[5]),
    .Q(_015_[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _130_ (
    .C(_016_),
    .CE(_001_),
    .D(_011_[6]),
    .Q(_015_[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _131_ (
    .C(_016_),
    .CE(_001_),
    .D(_011_[7]),
    .Q(_015_[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _132_ (
    .C(_016_),
    .CE(_005_),
    .D(_014_[0]),
    .Q(\stimIn[3] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _133_ (
    .C(_016_),
    .CE(_005_),
    .D(_014_[1]),
    .Q(\stimIn[3] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _134_ (
    .C(_016_),
    .CE(_005_),
    .D(_014_[2]),
    .Q(\stimIn[3] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _135_ (
    .C(_016_),
    .CE(_005_),
    .D(_014_[3]),
    .Q(\stimIn[3] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _136_ (
    .C(_016_),
    .CE(_005_),
    .D(_014_[4]),
    .Q(\stimIn[3] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _137_ (
    .C(_016_),
    .CE(_005_),
    .D(_014_[5]),
    .Q(\stimIn[3] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _138_ (
    .C(_016_),
    .CE(_005_),
    .D(_014_[6]),
    .Q(\stimIn[3] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _139_ (
    .C(_016_),
    .CE(_005_),
    .D(_014_[7]),
    .Q(\stimIn[3] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _140_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Xout [0]),
    .Q(\vectOut[0] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _141_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Xout [1]),
    .Q(\vectOut[0] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _142_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Xout [2]),
    .Q(\vectOut[0] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _143_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Xout [3]),
    .Q(\vectOut[0] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _144_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Xout [4]),
    .Q(\vectOut[0] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _145_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Xout [5]),
    .Q(\vectOut[0] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _146_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Xout [6]),
    .Q(\vectOut[0] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _147_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Xout [7]),
    .Q(\vectOut[0] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _148_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [8]),
    .Q(\vectOut[1] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _149_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [9]),
    .Q(\vectOut[1] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _150_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [10]),
    .Q(\vectOut[1] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _151_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [11]),
    .Q(\vectOut[1] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _152_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [12]),
    .Q(\vectOut[1] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _153_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [13]),
    .Q(\vectOut[1] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _154_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [14]),
    .Q(\vectOut[1] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:42.5-62.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _155_ (
    .C(_016_),
    .CE(_000_),
    .D(\u_fir_pe.Yout [15]),
    .Q(\vectOut[1] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:20.5-23.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _156_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(_008_[0]),
    .Q(counter[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:20.5-23.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _157_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(_008_[1]),
    .Q(counter[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:20.5-23.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _158_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(_008_[2]),
    .Q(counter[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../fir_pe_wrapper.v:20.5-23.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _159_ (
    .C(\u_fir_pe.clk ),
    .CE(1'h1),
    .D(_008_[3]),
    .Q(counter[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:29.14-29.23|/usr/local/bin/../share/yosys/mul2dsp.v:91.5-95.4|/usr/local/bin/../share/yosys/mul2dsp.v:253.6-257.5|/usr/local/bin/../share/yosys/xilinx/xc7_dsp_map.v:30.4-48.3" *)
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(1'h1),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _160_ (
    .A({ 22'h000000, Xin }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B({ 10'h000, Cin }),
    .BCIN(18'h00000),
    .C({ 32'h00000000, Yin }),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .CEP(1'h1),
    .CLK(\u_fir_pe.clk ),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h35),
    .P({ _012_, \u_fir_pe.y  }),
    .PCIN(48'h000000000000),
    .RSTP(1'h0)
  );
  (* keep = 32'd1 *)
  IBUF _161_ (
    .I(Addr_emu[0]),
    .O(_017_[3])
  );
  (* keep = 32'd1 *)
  IBUF _162_ (
    .I(Addr_emu[1]),
    .O(_017_[2])
  );
  (* keep = 32'd1 *)
  IBUF _163_ (
    .I(Addr_emu[2]),
    .O(_013_[2])
  );
  (* keep = 32'd1 *)
  IBUF _164_ (
    .I(Din_emu[0]),
    .O(_014_[0])
  );
  (* keep = 32'd1 *)
  IBUF _165_ (
    .I(Din_emu[1]),
    .O(_014_[1])
  );
  (* keep = 32'd1 *)
  IBUF _166_ (
    .I(Din_emu[2]),
    .O(_014_[2])
  );
  (* keep = 32'd1 *)
  IBUF _167_ (
    .I(Din_emu[3]),
    .O(_014_[3])
  );
  (* keep = 32'd1 *)
  IBUF _168_ (
    .I(Din_emu[4]),
    .O(_014_[4])
  );
  (* keep = 32'd1 *)
  IBUF _169_ (
    .I(Din_emu[5]),
    .O(_014_[5])
  );
  (* keep = 32'd1 *)
  IBUF _170_ (
    .I(Din_emu[6]),
    .O(_014_[6])
  );
  (* keep = 32'd1 *)
  IBUF _171_ (
    .I(Din_emu[7]),
    .O(_014_[7])
  );
  (* keep = 32'd1 *)
  OBUF _172_ (
    .I(_015_[0]),
    .O(Dout_emu[0])
  );
  (* keep = 32'd1 *)
  OBUF _173_ (
    .I(_015_[1]),
    .O(Dout_emu[1])
  );
  (* keep = 32'd1 *)
  OBUF _174_ (
    .I(_015_[2]),
    .O(Dout_emu[2])
  );
  (* keep = 32'd1 *)
  OBUF _175_ (
    .I(_015_[3]),
    .O(Dout_emu[3])
  );
  (* keep = 32'd1 *)
  OBUF _176_ (
    .I(_015_[4]),
    .O(Dout_emu[4])
  );
  (* keep = 32'd1 *)
  OBUF _177_ (
    .I(_015_[5]),
    .O(Dout_emu[5])
  );
  (* keep = 32'd1 *)
  OBUF _178_ (
    .I(_015_[6]),
    .O(Dout_emu[6])
  );
  (* keep = 32'd1 *)
  OBUF _179_ (
    .I(_015_[7]),
    .O(Dout_emu[7])
  );
  (* keep = 32'd1 *)
  OBUF _180_ (
    .I(counter[3]),
    .O(clk_LED)
  );
  (* keep = 32'd1 *)
  IBUF _181_ (
    .I(clk_dut),
    .O(_010_)
  );
  (* keep = 32'd1 *)
  IBUF _182_ (
    .I(clk_emu),
    .O(_009_)
  );
  (* keep = 32'd1 *)
  IBUF _183_ (
    .I(get_emu),
    .O(_017_[0])
  );
  (* keep = 32'd1 *)
  IBUF _184_ (
    .I(load_emu),
    .O(_017_[1])
  );
  assign _007_[3:1] = counter[3:1];
  assign _013_[1:0] = { _017_[2], _017_[3] };
  assign Xout = \u_fir_pe.Xout ;
  assign Yout = \u_fir_pe.Yout ;
  assign \u_fir_pe.Cin  = Cin;
  assign \u_fir_pe.Xin  = Xin;
  assign \u_fir_pe.Yin  = Yin;
endmodule
