/* Generated by Yosys 0.38+88 (git sha1 38f1b0b12, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "../../../source/ALU_wrapper.v:7.1-182.10" *)
module ALU_wrapper(clk, reset, ABCmd_i, LoadA_i, LoadB_i, LoadCmd_i, ACC_o, Done_o, Done_LED);
  (* src = "../../../source/ALU_wrapper.v:161.5-180.8" *)
  wire [7:0] _000_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _001_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _002_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _003_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _004_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU8.v:90.11-90.51|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4" *)
  wire [4:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU8.v:90.11-90.51|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [4:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU8.v:90.11-90.51|/usr/local/bin/../share/yosys/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 7" *)
  wire [7:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU8.v:90.11-90.51|/usr/local/bin/../share/yosys/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "5 6 7" *)
  wire [7:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU8.v:89.11-89.52|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4" *)
  wire [4:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU8.v:89.11-89.52|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [4:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU8.v:89.11-89.52|/usr/local/bin/../share/yosys/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 7" *)
  wire [7:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU8.v:89.11-89.52|/usr/local/bin/../share/yosys/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "5 6 7" *)
  wire [7:0] _029_;
  wire _030_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:0.0-0.0|../../../source/ALU_wrapper.v:55.13-79.20|/usr/local/bin/../share/yosys/techmap.v:133.22-133.23" *)
  (* unused_bits = "9 10 12 13 14 16 18" *)
  wire [18:0] _031_;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _032_;
  wire [7:0] _033_;
  wire _034_;
  wire _035_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:0.0-0.0|../../../source/ALU_wrapper.v:55.13-79.20|/usr/local/bin/../share/yosys/techmap.v:571.28-571.29" *)
  (* unused_bits = "0 1 3 4 5" *)
  wire [5:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:0.0-0.0|../../../source/ALU_wrapper.v:55.13-79.20|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _039_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _042_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _043_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _044_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _045_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _046_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _047_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _048_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _049_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _050_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _051_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _052_;
  (* src = "../../../source/ALU_wrapper.v:16.17-16.24" *)
  input [7:0] ABCmd_i;
  wire [7:0] ABCmd_i;
  (* src = "../../../source/ALU_wrapper.v:28.16-28.19" *)
  wire [7:0] ACC;
  (* src = "../../../source/ALU_wrapper.v:17.18-17.23" *)
  output [7:0] ACC_o;
  wire [7:0] ACC_o;
  (* src = "../../../source/ALU_wrapper.v:26.16-26.18" *)
  wire [7:0] AI;
  (* src = "../../../source/ALU_wrapper.v:36.22-36.24" *)
  wire AN;
  (* src = "../../../source/ALU_wrapper.v:34.10-34.13" *)
  wire BCD;
  (* src = "../../../source/ALU_wrapper.v:27.16-27.18" *)
  wire [7:0] BI;
  (* src = "../../../source/ALU_wrapper.v:32.10-32.12" *)
  wire CI;
  (* src = "../../../source/ALU_wrapper.v:20.12-20.20" *)
  output Done_LED;
  wire Done_LED;
  (* src = "../../../source/ALU_wrapper.v:18.12-18.18" *)
  output Done_o;
  wire Done_o;
  (* src = "../../../source/ALU_wrapper.v:36.26-36.28" *)
  wire HC;
  (* src = "../../../source/ALU_wrapper.v:13.11-13.18" *)
  input LoadA_i;
  wire LoadA_i;
  (* src = "../../../source/ALU_wrapper.v:14.11-14.18" *)
  input LoadB_i;
  wire LoadB_i;
  (* src = "../../../source/ALU_wrapper.v:15.11-15.20" *)
  input LoadCmd_i;
  wire LoadCmd_i;
  (* src = "../../../source/ALU_wrapper.v:35.10-35.13" *)
  wire MUL;
  (* src = "../../../source/ALU_wrapper.v:47.32-47.39" *)
  wire OutFlag;
  (* src = "../../../source/ALU_wrapper.v:31.16-31.22" *)
  wire [3:0] alu_op;
  (* src = "../../../source/ALU_wrapper.v:11.8-11.11" *)
  input clk;
  wire clk;
  (* src = "../../../source/ALU_wrapper.v:37.17-37.25" *)
  wire [15:0] mult_out;
  (* src = "../../../source/ALU_wrapper.v:24.15-24.17" *)
  wire [7:0] rA;
  (* src = "../../../source/ALU_wrapper.v:24.19-24.21" *)
  wire [7:0] rB;
  (* src = "../../../source/ALU_wrapper.v:30.16-30.20" *)
  wire [7:0] rCmd;
  (* src = "../../../source/ALU_wrapper.v:12.8-12.13" *)
  input reset;
  wire reset;
  (* src = "../../../source/ALU_wrapper.v:33.10-33.13" *)
  wire shr;
  (* src = "../../../source/ALU_wrapper.v:46.15-46.20" *)
  wire [2:0] state;
  (* hdlname = "u_ALU8 AI" *)
  (* src = "../../../source/ALU8.v:23.14-23.16" *)
  wire [7:0] \u_ALU8.AI ;
  (* hdlname = "u_ALU8 AI7" *)
  (* src = "../../../source/ALU8.v:40.6-40.9" *)
  wire \u_ALU8.AI7 ;
  (* hdlname = "u_ALU8 BCD" *)
  (* src = "../../../source/ALU8.v:26.8-26.11" *)
  wire \u_ALU8.BCD ;
  (* hdlname = "u_ALU8 BI" *)
  (* src = "../../../source/ALU8.v:24.14-24.16" *)
  wire [7:0] \u_ALU8.BI ;
  (* hdlname = "u_ALU8 BI7" *)
  (* src = "../../../source/ALU8.v:41.6-41.9" *)
  wire \u_ALU8.BI7 ;
  (* hdlname = "u_ALU8 CI" *)
  (* src = "../../../source/ALU8.v:25.8-25.10" *)
  wire \u_ALU8.CI ;
  (* hdlname = "u_ALU8 HC" *)
  (* src = "../../../source/ALU8.v:32.9-32.11" *)
  wire \u_ALU8.HC ;
  (* hdlname = "u_ALU8 N" *)
  (* src = "../../../source/ALU8.v:31.9-31.10" *)
  wire \u_ALU8.N ;
  (* hdlname = "u_ALU8 OUT" *)
  (* src = "../../../source/ALU8.v:27.15-27.18" *)
  wire [7:0] \u_ALU8.OUT ;
  (* hdlname = "u_ALU8 adder_CI" *)
  (* src = "../../../source/ALU8.v:48.6-48.14" *)
  wire \u_ALU8.adder_CI ;
  (* hdlname = "u_ALU8 op" *)
  (* src = "../../../source/ALU8.v:22.14-22.16" *)
  wire [3:0] \u_ALU8.op ;
  (* hdlname = "u_ALU8 shr" *)
  (* src = "../../../source/ALU8.v:21.8-21.11" *)
  wire \u_ALU8.shr ;
  (* hdlname = "u_ALU8 temp" *)
  (* src = "../../../source/ALU8.v:47.12-47.16" *)
  wire [8:0] \u_ALU8.temp ;
  (* hdlname = "u_ALU8 temp_BI" *)
  (* src = "../../../source/ALU8.v:44.11-44.18" *)
  wire [7:0] \u_ALU8.temp_BI ;
  (* hdlname = "u_ALU8 temp_HC" *)
  (* src = "../../../source/ALU8.v:83.6-83.13" *)
  wire \u_ALU8.temp_HC ;
  (* hdlname = "u_ALU8 temp_h" *)
  (* src = "../../../source/ALU8.v:46.11-46.17" *)
  wire [4:0] \u_ALU8.temp_h ;
  (* hdlname = "u_ALU8 temp_l" *)
  (* src = "../../../source/ALU8.v:45.11-45.17" *)
  wire [4:0] \u_ALU8.temp_l ;
  (* hdlname = "u_ALU8 temp_logic" *)
  (* src = "../../../source/ALU8.v:43.11-43.21" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [8:0] \u_ALU8.temp_logic ;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _053_ (
    .I0(_040_[1]),
    .I1(state[0]),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _054_ (
    .I0(state[2]),
    .I1(state[1]),
    .O(_040_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _055_ (
    .I0(state[0]),
    .I1(_040_[1]),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _056_ (
    .I0(_039_[0]),
    .I1(state[1]),
    .O(OutFlag)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _057_ (
    .I0(state[0]),
    .I1(state[2]),
    .O(_039_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4277203184)
  ) _058_ (
    .I0(\u_ALU8.temp_l [2]),
    .I1(\u_ALU8.temp_l [1]),
    .I2(\u_ALU8.temp_l [4]),
    .I3(\u_ALU8.temp_l [3]),
    .I4(BCD),
    .O(HC)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hccccaaaaf0f0ff00)
  ) _059_ (
    .I0(mult_out[8]),
    .I1(mult_out[0]),
    .I2(\u_ALU8.temp_l [0]),
    .I3(HC),
    .I4(_038_[4]),
    .I5(MUL),
    .O(_000_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _060_ (
    .I0(state[0]),
    .I1(state[1]),
    .I2(state[2]),
    .O(_038_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf0f0aaaaff00cccc)
  ) _061_ (
    .I0(mult_out[9]),
    .I1(\u_ALU8.temp_h [3]),
    .I2(mult_out[1]),
    .I3(\u_ALU8.temp_l [1]),
    .I4(_038_[4]),
    .I5(MUL),
    .O(_000_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h000000008000ffff)
  ) _062_ (
    .I0(_052_[0]),
    .I1(_052_[1]),
    .I2(_052_[2]),
    .I3(_052_[3]),
    .I4(_052_[4]),
    .I5(_052_[5]),
    .O(_000_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _063_ (
    .I0(\u_ALU8.temp_l [1]),
    .I1(\u_ALU8.temp_l [2]),
    .O(_052_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _064_ (
    .I0(\u_ALU8.temp_l [0]),
    .I1(MUL),
    .O(_052_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0005000300000000)
  ) _065_ (
    .I0(mult_out[2]),
    .I1(\u_ALU8.temp_l [2]),
    .I2(state[1]),
    .I3(state[0]),
    .I4(MUL),
    .I5(state[2]),
    .O(_052_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h01)
  ) _066_ (
    .I0(\u_ALU8.temp_h [0]),
    .I1(\u_ALU8.temp_h [3]),
    .I2(\u_ALU8.temp_l [3]),
    .O(_052_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _067_ (
    .I0(\u_ALU8.temp_h [1]),
    .I1(\u_ALU8.temp_h [2]),
    .O(_052_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd15724527)
  ) _068_ (
    .I0(state[1]),
    .I1(state[0]),
    .I2(state[2]),
    .I3(mult_out[10]),
    .I4(MUL),
    .O(_052_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h33333333aaaaf00f)
  ) _069_ (
    .I0(mult_out[11]),
    .I1(_050_[1]),
    .I2(\u_ALU8.BI7 ),
    .I3(_050_[3]),
    .I4(MUL),
    .I5(_038_[4]),
    .O(_000_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h53)
  ) _070_ (
    .I0(mult_out[3]),
    .I1(\u_ALU8.temp_l [3]),
    .I2(MUL),
    .O(_050_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _071_ (
    .I0(rB[7]),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'haaaaaaaaf30fcf00)
  ) _072_ (
    .I0(CI),
    .I1(alu_op[1]),
    .I2(alu_op[0]),
    .I3(\u_ALU8.AI7 ),
    .I4(rB[7]),
    .I5(shr),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _073_ (
    .I0(_003_),
    .I1(_004_),
    .O(_001_),
    .S(alu_op[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h1)
  ) _074_ (
    .I0(rB[7]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _075_ (
    .I0(_005_),
    .I1(1'h0),
    .O(_002_),
    .S(alu_op[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _076_ (
    .I0(_001_),
    .I1(_002_),
    .O(\u_ALU8.BI7 ),
    .S(alu_op[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff1f00ff00e0ff)
  ) _077_ (
    .I0(\u_ALU8.temp_h [1]),
    .I1(\u_ALU8.temp_h [2]),
    .I2(BCD),
    .I3(\u_ALU8.temp_h [3]),
    .I4(\u_ALU8.temp_h [4]),
    .I5(\u_ALU8.AI7 ),
    .O(_050_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf0f0aaaaff003333)
  ) _078_ (
    .I0(mult_out[12]),
    .I1(_045_[1]),
    .I2(mult_out[4]),
    .I3(\u_ALU8.temp_h [0]),
    .I4(_038_[4]),
    .I5(MUL),
    .O(_000_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd8191)
  ) _079_ (
    .I0(\u_ALU8.temp_h [1]),
    .I1(\u_ALU8.temp_h [2]),
    .I2(BCD),
    .I3(\u_ALU8.temp_h [3]),
    .I4(\u_ALU8.temp_h [4]),
    .O(_045_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3433754624)
  ) _080_ (
    .I0(mult_out[13]),
    .I1(mult_out[5]),
    .I2(\u_ALU8.temp_h [1]),
    .I3(_038_[4]),
    .I4(MUL),
    .O(_000_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3433754624)
  ) _081_ (
    .I0(mult_out[14]),
    .I1(mult_out[6]),
    .I2(\u_ALU8.temp_h [2]),
    .I3(_038_[4]),
    .I4(MUL),
    .O(_000_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3433754624)
  ) _082_ (
    .I0(mult_out[15]),
    .I1(mult_out[7]),
    .I2(\u_ALU8.temp_h [3]),
    .I3(_038_[4]),
    .I4(MUL),
    .O(_000_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _083_ (
    .I0(shr),
    .I1(rA[0]),
    .O(\u_ALU8.temp_logic [8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0700)
  ) _084_ (
    .I0(alu_op[3]),
    .I1(alu_op[2]),
    .I2(shr),
    .I3(CI),
    .O(\u_ALU8.adder_CI )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h035c)
  ) _085_ (
    .I0(_044_[0]),
    .I1(rB[0]),
    .I2(alu_op[3]),
    .I3(alu_op[2]),
    .O(\u_ALU8.temp_BI [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h555555550cf030ff)
  ) _086_ (
    .I0(rA[1]),
    .I1(alu_op[1]),
    .I2(alu_op[0]),
    .I3(rA[0]),
    .I4(rB[0]),
    .I5(shr),
    .O(_044_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h035c)
  ) _087_ (
    .I0(_043_[0]),
    .I1(rB[1]),
    .I2(alu_op[3]),
    .I3(alu_op[2]),
    .O(\u_ALU8.temp_BI [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h555555550cf030ff)
  ) _088_ (
    .I0(rA[2]),
    .I1(alu_op[1]),
    .I2(alu_op[0]),
    .I3(rA[1]),
    .I4(rB[1]),
    .I5(shr),
    .O(_043_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h035c)
  ) _089_ (
    .I0(_042_[0]),
    .I1(rB[2]),
    .I2(alu_op[3]),
    .I3(alu_op[2]),
    .O(\u_ALU8.temp_BI [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h555555550cf030ff)
  ) _090_ (
    .I0(rA[3]),
    .I1(alu_op[1]),
    .I2(alu_op[0]),
    .I3(rA[2]),
    .I4(rB[2]),
    .I5(shr),
    .O(_042_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h035c)
  ) _091_ (
    .I0(_041_[0]),
    .I1(rB[3]),
    .I2(alu_op[3]),
    .I3(alu_op[2]),
    .O(\u_ALU8.temp_BI [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h555555550cf030ff)
  ) _092_ (
    .I0(rA[4]),
    .I1(alu_op[1]),
    .I2(alu_op[0]),
    .I3(rA[3]),
    .I4(rB[3]),
    .I5(shr),
    .O(_041_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h035c)
  ) _093_ (
    .I0(_049_[3]),
    .I1(rB[4]),
    .I2(alu_op[3]),
    .I3(alu_op[2]),
    .O(\u_ALU8.temp_BI [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h555555550cf030ff)
  ) _094_ (
    .I0(rA[5]),
    .I1(alu_op[1]),
    .I2(alu_op[0]),
    .I3(rA[4]),
    .I4(rB[4]),
    .I5(shr),
    .O(_049_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h035c)
  ) _095_ (
    .I0(_048_[3]),
    .I1(rB[5]),
    .I2(alu_op[3]),
    .I3(alu_op[2]),
    .O(\u_ALU8.temp_BI [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h555555550cf030ff)
  ) _096_ (
    .I0(rA[6]),
    .I1(alu_op[1]),
    .I2(alu_op[0]),
    .I3(rA[5]),
    .I4(rB[5]),
    .I5(shr),
    .O(_048_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h035c)
  ) _097_ (
    .I0(_047_[3]),
    .I1(rB[6]),
    .I2(alu_op[3]),
    .I3(alu_op[2]),
    .O(\u_ALU8.temp_BI [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h555555550cf030ff)
  ) _098_ (
    .I0(\u_ALU8.AI7 ),
    .I1(alu_op[1]),
    .I2(alu_op[0]),
    .I3(rA[6]),
    .I4(rB[6]),
    .I5(shr),
    .O(_047_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hcdcdcfcd3f047733)
  ) _099_ (
    .I0(_051_[0]),
    .I1(state[2]),
    .I2(_036_[2]),
    .I3(_031_[8]),
    .I4(state[1]),
    .I5(state[0]),
    .O(_037_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00af000e0ecfff00)
  ) _100_ (
    .I0(_051_[0]),
    .I1(_031_[8]),
    .I2(_036_[2]),
    .I3(state[2]),
    .I4(state[1]),
    .I5(state[0]),
    .O(_037_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h000050f0f0113000)
  ) _101_ (
    .I0(_051_[0]),
    .I1(_031_[8]),
    .I2(_036_[2]),
    .I3(state[1]),
    .I4(state[2]),
    .I5(state[0]),
    .O(_037_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h14e1)
  ) _102_ (
    .I0(alu_op[3]),
    .I1(rB[4]),
    .I2(alu_op[2]),
    .I3(_049_[3]),
    .O(_023_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h14e1)
  ) _103_ (
    .I0(alu_op[3]),
    .I1(rB[5]),
    .I2(alu_op[2]),
    .I3(_048_[3]),
    .O(_023_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h14e1)
  ) _104_ (
    .I0(alu_op[3]),
    .I1(rB[6]),
    .I2(alu_op[2]),
    .I3(_047_[3]),
    .O(_023_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h14e1)
  ) _105_ (
    .I0(alu_op[3]),
    .I1(rB[7]),
    .I2(alu_op[2]),
    .I3(_046_[3]),
    .O(_023_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h555555550cf030ff)
  ) _106_ (
    .I0(CI),
    .I1(alu_op[1]),
    .I2(alu_op[0]),
    .I3(\u_ALU8.AI7 ),
    .I4(rB[7]),
    .I5(shr),
    .O(_046_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h14e1)
  ) _107_ (
    .I0(alu_op[3]),
    .I1(rB[0]),
    .I2(alu_op[2]),
    .I3(_044_[0]),
    .O(_027_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h14e1)
  ) _108_ (
    .I0(alu_op[3]),
    .I1(rB[1]),
    .I2(alu_op[2]),
    .I3(_043_[0]),
    .O(_027_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h14e1)
  ) _109_ (
    .I0(alu_op[3]),
    .I1(rB[2]),
    .I2(alu_op[2]),
    .I3(_042_[0]),
    .O(_027_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h14e1)
  ) _110_ (
    .I0(alu_op[3]),
    .I1(rB[3]),
    .I2(alu_op[2]),
    .I3(_041_[0]),
    .O(_027_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _111_ (
    .I0(_040_[1]),
    .I1(state[0]),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _112_ (
    .I0(_040_[1]),
    .I1(state[0]),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _113_ (
    .I0(_040_[1]),
    .I1(state[0]),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _114_ (
    .I0(_040_[1]),
    .I1(state[0]),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _115_ (
    .I0(_040_[1]),
    .I1(state[0]),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _116_ (
    .I0(_040_[1]),
    .I1(state[0]),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _117_ (
    .I0(_040_[1]),
    .I1(state[0]),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _118_ (
    .I0(state[0]),
    .I1(_040_[1]),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _119_ (
    .I0(state[0]),
    .I1(_040_[1]),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _120_ (
    .I0(state[0]),
    .I1(_040_[1]),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _121_ (
    .I0(state[0]),
    .I1(_040_[1]),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _122_ (
    .I0(state[0]),
    .I1(_040_[1]),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _123_ (
    .I0(state[0]),
    .I1(_040_[1]),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _124_ (
    .I0(state[0]),
    .I1(_040_[1]),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU8.v:90.11-90.51|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _125_ (
    .CI(1'h0),
    .CO(_022_[3:0]),
    .CYINIT(HC),
    .DI({ \u_ALU8.BI7 , \u_ALU8.temp_BI [6:4] }),
    .O(\u_ALU8.temp_h [3:0]),
    .S(_023_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU8.v:90.11-90.51|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _126_ (
    .CI(_022_[3]),
    .CO({ _024_[7:5], _022_[4] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _025_[7:5], \u_ALU8.temp_h [4] }),
    .S({ 3'h0, \u_ALU8.temp_logic [8] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU8.v:89.11-89.52|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _127_ (
    .CI(1'h0),
    .CO(_026_[3:0]),
    .CYINIT(\u_ALU8.adder_CI ),
    .DI(\u_ALU8.temp_BI [3:0]),
    .O(\u_ALU8.temp_l [3:0]),
    .S(_027_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU8.v:89.11-89.52|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _128_ (
    .CI(_026_[3]),
    .CO({ _028_[7:5], _026_[4] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _029_[7:5], \u_ALU8.temp_l [4] }),
    .S(4'h0)
  );
  BUFG _129_ (
    .I(_030_),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _130_ (
    .C(_034_),
    .CE(_006_),
    .CLR(_035_),
    .D(alu_op[0]),
    .Q(rB[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _131_ (
    .C(_034_),
    .CE(_007_),
    .CLR(_035_),
    .D(alu_op[1]),
    .Q(rB[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _132_ (
    .C(_034_),
    .CE(_008_),
    .CLR(_035_),
    .D(alu_op[2]),
    .Q(rB[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _133_ (
    .C(_034_),
    .CE(_009_),
    .CLR(_035_),
    .D(alu_op[3]),
    .Q(rB[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _134_ (
    .C(_034_),
    .CE(_010_),
    .CLR(_035_),
    .D(CI),
    .Q(rB[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _135_ (
    .C(_034_),
    .CE(_011_),
    .CLR(_035_),
    .D(shr),
    .Q(rB[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _136_ (
    .C(_034_),
    .CE(_012_),
    .CLR(_035_),
    .D(BCD),
    .Q(rB[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _137_ (
    .C(_034_),
    .CE(_013_),
    .CLR(_035_),
    .D(MUL),
    .Q(rB[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:161.5-180.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _138_ (
    .C(_034_),
    .CE(_039_[0]),
    .CLR(_035_),
    .D(_000_[0]),
    .Q(_033_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:161.5-180.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _139_ (
    .C(_034_),
    .CE(_039_[0]),
    .CLR(_035_),
    .D(_000_[1]),
    .Q(_033_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:161.5-180.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _140_ (
    .C(_034_),
    .CE(_039_[0]),
    .CLR(_035_),
    .D(_000_[2]),
    .Q(_033_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:161.5-180.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _141_ (
    .C(_034_),
    .CE(_039_[0]),
    .CLR(_035_),
    .D(_000_[3]),
    .Q(_033_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:161.5-180.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _142_ (
    .C(_034_),
    .CE(_039_[0]),
    .CLR(_035_),
    .D(_000_[4]),
    .Q(_033_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:161.5-180.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _143_ (
    .C(_034_),
    .CE(_039_[0]),
    .CLR(_035_),
    .D(_000_[5]),
    .Q(_033_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:161.5-180.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _144_ (
    .C(_034_),
    .CE(_039_[0]),
    .CLR(_035_),
    .D(_000_[6]),
    .Q(_033_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:161.5-180.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _145_ (
    .C(_034_),
    .CE(_039_[0]),
    .CLR(_035_),
    .D(_000_[7]),
    .Q(_033_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _146_ (
    .C(_034_),
    .CE(_014_),
    .CLR(_035_),
    .D(alu_op[0]),
    .Q(rA[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _147_ (
    .C(_034_),
    .CE(_015_),
    .CLR(_035_),
    .D(alu_op[1]),
    .Q(rA[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _148_ (
    .C(_034_),
    .CE(_016_),
    .CLR(_035_),
    .D(alu_op[2]),
    .Q(rA[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _149_ (
    .C(_034_),
    .CE(_017_),
    .CLR(_035_),
    .D(alu_op[3]),
    .Q(rA[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _150_ (
    .C(_034_),
    .CE(_018_),
    .CLR(_035_),
    .D(CI),
    .Q(rA[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _151_ (
    .C(_034_),
    .CE(_019_),
    .CLR(_035_),
    .D(shr),
    .Q(rA[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _152_ (
    .C(_034_),
    .CE(_020_),
    .CLR(_035_),
    .D(BCD),
    .Q(rA[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:114.5-124.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _153_ (
    .C(_034_),
    .CE(_021_),
    .CLR(_035_),
    .D(MUL),
    .Q(\u_ALU8.AI7 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:49.5-81.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:42.41-42.97" *)
  FDPE #(
    .INIT(1'hx)
  ) _154_ (
    .C(_034_),
    .CE(1'h1),
    .D(_037_[0]),
    .PRE(_035_),
    .Q(state[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:49.5-81.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _155_ (
    .C(_034_),
    .CE(1'h1),
    .CLR(_035_),
    .D(_037_[1]),
    .Q(state[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:49.5-81.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _156_ (
    .C(_034_),
    .CE(1'h1),
    .CLR(_035_),
    .D(_037_[2]),
    .Q(state[2])
  );
  (* keep = 32'd1 *)
  IBUF _157_ (
    .I(ABCmd_i[0]),
    .O(alu_op[0])
  );
  (* keep = 32'd1 *)
  IBUF _158_ (
    .I(ABCmd_i[1]),
    .O(alu_op[1])
  );
  (* keep = 32'd1 *)
  IBUF _159_ (
    .I(ABCmd_i[2]),
    .O(alu_op[2])
  );
  (* keep = 32'd1 *)
  IBUF _160_ (
    .I(ABCmd_i[3]),
    .O(alu_op[3])
  );
  (* keep = 32'd1 *)
  IBUF _161_ (
    .I(ABCmd_i[4]),
    .O(CI)
  );
  (* keep = 32'd1 *)
  IBUF _162_ (
    .I(ABCmd_i[5]),
    .O(shr)
  );
  (* keep = 32'd1 *)
  IBUF _163_ (
    .I(ABCmd_i[6]),
    .O(BCD)
  );
  (* keep = 32'd1 *)
  IBUF _164_ (
    .I(ABCmd_i[7]),
    .O(MUL)
  );
  (* keep = 32'd1 *)
  OBUF _165_ (
    .I(_033_[0]),
    .O(ACC_o[0])
  );
  (* keep = 32'd1 *)
  OBUF _166_ (
    .I(_033_[1]),
    .O(ACC_o[1])
  );
  (* keep = 32'd1 *)
  OBUF _167_ (
    .I(_033_[2]),
    .O(ACC_o[2])
  );
  (* keep = 32'd1 *)
  OBUF _168_ (
    .I(_033_[3]),
    .O(ACC_o[3])
  );
  (* keep = 32'd1 *)
  OBUF _169_ (
    .I(_033_[4]),
    .O(ACC_o[4])
  );
  (* keep = 32'd1 *)
  OBUF _170_ (
    .I(_033_[5]),
    .O(ACC_o[5])
  );
  (* keep = 32'd1 *)
  OBUF _171_ (
    .I(_033_[6]),
    .O(ACC_o[6])
  );
  (* keep = 32'd1 *)
  OBUF _172_ (
    .I(_033_[7]),
    .O(ACC_o[7])
  );
  (* keep = 32'd1 *)
  OBUF _173_ (
    .I(OutFlag),
    .O(Done_LED)
  );
  (* keep = 32'd1 *)
  OBUF _174_ (
    .I(OutFlag),
    .O(Done_o)
  );
  (* keep = 32'd1 *)
  IBUF _175_ (
    .I(LoadA_i),
    .O(_051_[0])
  );
  (* keep = 32'd1 *)
  IBUF _176_ (
    .I(LoadB_i),
    .O(_031_[8])
  );
  (* keep = 32'd1 *)
  IBUF _177_ (
    .I(LoadCmd_i),
    .O(_036_[2])
  );
  (* keep = 32'd1 *)
  IBUF _178_ (
    .I(clk),
    .O(_030_)
  );
  (* keep = 32'd1 *)
  IBUF _179_ (
    .I(reset),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/ALU_wrapper.v:142.23-142.30|/usr/local/bin/../share/yosys/mul2dsp.v:91.5-95.4|/usr/local/bin/../share/yosys/mul2dsp.v:253.6-257.5|/usr/local/bin/../share/yosys/xilinx/xc7_dsp_map.v:30.4-48.3" *)
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(32'sd0),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _180_ (
    .A({ 22'h000000, \u_ALU8.AI7 , rA[6:0] }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B({ 10'h000, rB }),
    .BCIN(18'h00000),
    .C(48'h000000000000),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h05),
    .P({ _032_, mult_out }),
    .PCIN(48'h000000000000)
  );
  assign _051_[5:1] = { state[0], state[2:1], _036_[2], _031_[8] };
  assign _040_[0] = state[0];
  assign { _045_[5:2], _045_[0] } = { MUL, _038_[4], \u_ALU8.temp_h [0], mult_out[4], mult_out[12] };
  assign _044_[3:1] = { alu_op[2], alu_op[3], rB[0] };
  assign _046_[2:0] = { alu_op[2], rB[7], alu_op[3] };
  assign _039_[1] = state[1];
  assign _048_[2:0] = { alu_op[2], rB[5], alu_op[3] };
  assign _042_[3:1] = { alu_op[2], alu_op[3], rB[2] };
  assign _041_[3:1] = { alu_op[2], alu_op[3], rB[3] };
  assign { _038_[5], _038_[3:0] } = { MUL, HC, \u_ALU8.temp_l [0], mult_out[0], mult_out[8] };
  assign _043_[3:1] = { alu_op[2], alu_op[3], rB[1] };
  assign _047_[2:0] = { alu_op[2], rB[6], alu_op[3] };
  assign _049_[2:0] = { alu_op[2], rB[4], alu_op[3] };
  assign { _050_[5:4], _050_[2], _050_[0] } = { _038_[4], MUL, \u_ALU8.BI7 , mult_out[11] };
  assign _023_[4] = \u_ALU8.temp_logic [8];
  assign _024_[4:0] = _022_;
  assign _025_[4:0] = \u_ALU8.temp_h ;
  assign _027_[4] = 1'h0;
  assign _028_[4:0] = _026_;
  assign _029_[4:0] = \u_ALU8.temp_l ;
  assign { _031_[17], _031_[15], _031_[11], _031_[7:0] } = 11'b1xxxxxxxxxx;
  assign ACC = { \u_ALU8.temp_h [3:0], \u_ALU8.temp_l [3:0] };
  assign AI = { \u_ALU8.AI7 , rA[6:0] };
  assign AN = \u_ALU8.temp_h [3];
  assign BI = rB;
  assign rA[7] = \u_ALU8.AI7 ;
  assign rCmd = { MUL, BCD, shr, CI, alu_op };
  assign \u_ALU8.AI  = { \u_ALU8.AI7 , rA[6:0] };
  assign \u_ALU8.BCD  = BCD;
  assign \u_ALU8.BI  = rB;
  assign \u_ALU8.CI  = CI;
  assign \u_ALU8.HC  = HC;
  assign \u_ALU8.N  = \u_ALU8.temp_h [3];
  assign \u_ALU8.OUT  = { \u_ALU8.temp_h [3:0], \u_ALU8.temp_l [3:0] };
  assign \u_ALU8.op  = alu_op;
  assign \u_ALU8.shr  = shr;
  assign \u_ALU8.temp  = { \u_ALU8.temp_h , \u_ALU8.temp_l [3:0] };
  assign \u_ALU8.temp_BI [7] = \u_ALU8.BI7 ;
  assign \u_ALU8.temp_HC  = HC;
endmodule
