#!/bin/sh

set -e
if [ -d cc65-2.13.3 ]
then
  echo "Source directory already exists, exiting."
  exit 1
fi
echo "*** Extracting source"
tar xjf cc65-sources-2.13.3.tar.bz2
echo "*** Applying patch"
patch -p0  <cc65-2.13.3-replica1.patch
cd cc65-2.13.3
echo "*** Building"
make -s -f make/gcc.mak
echo "*** Installing"
#sudo make -s -f make/gcc.mak install prefix=/usr/local/replica1
make -s -f make/gcc.mak install prefix=~/ETRI050_DesignKit/devel/Ref_Design/CPU_6502/simulation/Apple-1/cc65-2.13.3
echo "*** Done"
