-- ==============================================================
-- Generated by Vitis HLS v2024.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fxp_sqrt_top_fxp_sqrt_top_Pipeline_VITIS_LOOP_106_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln90 : IN STD_LOGIC_VECTOR (10 downto 0);
    s_4_out : OUT STD_LOGIC_VECTOR (12 downto 0);
    s_4_out_ap_vld : OUT STD_LOGIC;
    p_v_out : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_v_out_ap_vld : OUT STD_LOGIC;
    q_1_out : OUT STD_LOGIC_VECTOR (10 downto 0);
    q_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fxp_sqrt_top_fxp_sqrt_top_Pipeline_VITIS_LOOP_106_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln106_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sub_ln108_fu_130_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln108_reg_305 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln106_reg_310 : STD_LOGIC_VECTOR (0 downto 0);
    signal i1_fu_60 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_fu_136_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i1_load : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal s_12_fu_64 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal s_fu_219_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln90_cast_fu_103_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal q_star4_fu_68 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal q_star_fu_245_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal q6_fu_72 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal q_fu_253_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal empty_10_fu_236_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln_fu_179_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln108_fu_176_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln108_1_fu_170_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln108_fu_187_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln1_fu_199_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln112_fu_207_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_fu_162_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal s_2_fu_213_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal s_1_fu_193_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal empty_fu_228_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_9_fu_232_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fxp_sqrt_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fxp_sqrt_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    i1_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then 
                    i1_fu_60 <= i_fu_136_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i1_fu_60 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    q6_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    q6_fu_72 <= ap_const_lv11_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    q6_fu_72 <= q_fu_253_p3;
                end if;
            end if; 
        end if;
    end process;

    q_star4_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    q_star4_fu_68(1) <= '0';
                    q_star4_fu_68(2) <= '0';
                    q_star4_fu_68(3) <= '0';
                    q_star4_fu_68(4) <= '0';
                    q_star4_fu_68(5) <= '0';
                    q_star4_fu_68(6) <= '0';
                    q_star4_fu_68(7) <= '0';
                    q_star4_fu_68(8) <= '0';
                    q_star4_fu_68(9) <= '0';
                    q_star4_fu_68(10) <= '0';
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                                        q_star4_fu_68(10 downto 1) <= q_star_fu_245_p3(10 downto 1);
                end if;
            end if; 
        end if;
    end process;

    s_12_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    s_12_fu_64 <= zext_ln90_cast_fu_103_p1;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    s_12_fu_64 <= s_fu_219_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln106_reg_310 <= icmp_ln106_fu_142_p2;
                sub_ln108_reg_305 <= sub_ln108_fu_130_p2;
            end if;
        end if;
    end process;
    q_star4_fu_68(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln106_fu_142_p2)
    begin
        if (((icmp_ln106_fu_142_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, i1_fu_60, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i1_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i1_load <= i1_fu_60;
        end if; 
    end process;

    empty_10_fu_236_p3 <= 
        empty_fu_228_p1 when (tmp_fu_162_p3(0) = '1') else 
        empty_9_fu_232_p1;
    empty_9_fu_232_p1 <= q6_fu_72(10 - 1 downto 0);
    empty_fu_228_p1 <= q_star4_fu_68(10 - 1 downto 0);
    i_fu_136_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i1_load) + unsigned(ap_const_lv4_1));
    icmp_ln106_fu_142_p2 <= "1" when (ap_sig_allocacmp_i1_load = ap_const_lv4_B) else "0";
    or_ln1_fu_199_p3 <= (q_star4_fu_68 & ap_const_lv2_3);
    or_ln_fu_179_p3 <= (q6_fu_72 & ap_const_lv2_1);
    p_v_out <= empty_10_fu_236_p3;

    p_v_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln106_reg_310, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln106_reg_310 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_v_out_ap_vld <= ap_const_logic_1;
        else 
            p_v_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    q_1_out <= (empty_10_fu_236_p3 & ap_const_lv1_1);

    q_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln106_reg_310, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln106_reg_310 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            q_1_out_ap_vld <= ap_const_logic_1;
        else 
            q_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    q_fu_253_p3 <= (empty_10_fu_236_p3 & ap_const_lv1_1);
    q_star_fu_245_p3 <= (empty_10_fu_236_p3 & ap_const_lv1_0);
    s_1_fu_193_p2 <= std_logic_vector(unsigned(shl_ln108_1_fu_170_p2) - unsigned(shl_ln108_fu_187_p2));
    s_2_fu_213_p2 <= std_logic_vector(unsigned(shl_ln112_fu_207_p2) + unsigned(shl_ln108_1_fu_170_p2));
    s_4_out <= 
        s_2_fu_213_p2 when (tmp_fu_162_p3(0) = '1') else 
        s_1_fu_193_p2;

    s_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln106_reg_310, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln106_reg_310 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_4_out_ap_vld <= ap_const_logic_1;
        else 
            s_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    s_fu_219_p3 <= 
        s_2_fu_213_p2 when (tmp_fu_162_p3(0) = '1') else 
        s_1_fu_193_p2;
    shl_ln108_1_fu_170_p2 <= std_logic_vector(shift_left(unsigned(s_12_fu_64),to_integer(unsigned('0' & ap_const_lv13_1(13-1 downto 0)))));
    shl_ln108_fu_187_p2 <= std_logic_vector(shift_left(unsigned(or_ln_fu_179_p3),to_integer(unsigned('0' & zext_ln108_fu_176_p1(13-1 downto 0)))));
    shl_ln112_fu_207_p2 <= std_logic_vector(shift_left(unsigned(or_ln1_fu_199_p3),to_integer(unsigned('0' & zext_ln108_fu_176_p1(13-1 downto 0)))));
    sub_ln108_fu_130_p2 <= std_logic_vector(signed(ap_const_lv4_B) - signed(ap_sig_allocacmp_i1_load));
    tmp_fu_162_p3 <= s_12_fu_64(12 downto 12);
    zext_ln108_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln108_reg_305),13));
    zext_ln90_cast_fu_103_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln90),13));
end behav;
