/* Generated by Yosys 0.50+56 (git sha1 176131b50, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "../../../test_wrapper.v:6.1-105.10" *)
module test_wrapper(Din_emu, Dout_emu, Addr_emu, load_emu, get_emu, clk_emu, clk_dut);
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _000_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _001_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _002_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _003_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _004_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _005_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _006_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _007_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _008_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:88.18-88.86" *)
  wire _029_;
  (* force_downto = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:267.31-267.87|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 11" *)
  wire [11:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:267.31-267.87|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [11:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:271.22-271.53|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:271.22-271.53|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [3:0] _033_;
  wire _034_;
  wire _035_;
  (* force_downto = 32'd1 *)
  (* src = "../../../test_wrapper.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:137.23-137.24" *)
  (* unused_bits = "5 6 7" *)
  wire [7:0] _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  (* unused_bits = "2" *)
  wire [2:0] _041_;
  wire [7:0] _042_;
  wire [7:0] _043_;
  wire _044_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _045_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _046_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _047_;
  (* src = "../../../test_wrapper.v:31.17-31.27" *)
  wire [3:0] A_address0;
  (* src = "../../../test_wrapper.v:32.17-32.22" *)
  wire A_ce0;
  (* src = "../../../test_wrapper.v:26.17-26.21" *)
  wire [7:0] A_q0;
  (* src = "../../../test_wrapper.v:12.21-12.29" *)
  input [2:0] Addr_emu;
  wire [2:0] Addr_emu;
  (* src = "../../../test_wrapper.v:10.21-10.28" *)
  input [7:0] Din_emu;
  wire [7:0] Din_emu;
  (* src = "../../../test_wrapper.v:11.21-11.29" *)
  output [7:0] Dout_emu;
  wire [7:0] Dout_emu;
  (* src = "../../../test_wrapper.v:28.17-28.24" *)
  wire ap_done;
  (* src = "../../../test_wrapper.v:30.17-30.25" *)
  wire ap_ready;
  (* src = "../../../test_wrapper.v:33.17-33.26" *)
  wire [12:0] ap_return;
  (* src = "../../../test_wrapper.v:24.17-24.23" *)
  wire ap_rst;
  (* src = "../../../test_wrapper.v:25.17-25.25" *)
  wire ap_start;
  (* src = "../../../test_wrapper.v:14.21-14.28" *)
  input clk_dut;
  wire clk_dut;
  (* src = "../../../test_wrapper.v:13.40-13.47" *)
  input clk_emu;
  wire clk_emu;
  (* src = "../../../test_wrapper.v:13.31-13.38" *)
  input get_emu;
  wire get_emu;
  (* src = "../../../test_wrapper.v:13.21-13.29" *)
  input load_emu;
  wire load_emu;
  (* unused_bits = "2 3 4 5 6 7" *)
  wire [7:0] \stimIn[0] ;
  wire [7:0] \stimIn[1] ;
  (* hdlname = "u_test A_address0" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:32.15-32.25" *)
  wire [3:0] \u_test.A_address0 ;
  (* hdlname = "u_test A_ce0" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:33.10-33.15" *)
  wire \u_test.A_ce0 ;
  (* hdlname = "u_test A_ce0_local" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:60.8-60.19" *)
  wire \u_test.A_ce0_local ;
  (* hdlname = "u_test A_q0" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:34.14-34.18" *)
  wire [7:0] \u_test.A_q0 ;
  (* fsm_encoding = "none" *)
  (* hdlname = "u_test ap_CS_fsm" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:39.41-39.50" *)
  wire \u_test.ap_CS_fsm ;
  (* hdlname = "u_test ap_CS_fsm_pp0_stage0" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:40.9-40.29" *)
  wire \u_test.ap_CS_fsm_pp0_stage0 ;
  (* hdlname = "u_test ap_block_pp0_stage0" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:53.9-53.28" *)
  wire \u_test.ap_block_pp0_stage0 ;
  (* hdlname = "u_test ap_block_pp0_stage0_11001" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:50.9-50.34" *)
  wire \u_test.ap_block_pp0_stage0_11001 ;
  (* hdlname = "u_test ap_block_pp0_stage0_subdone" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:44.9-44.36" *)
  wire \u_test.ap_block_pp0_stage0_subdone ;
  (* hdlname = "u_test ap_clk" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:26.9-26.15" *)
  wire \u_test.ap_clk ;
  (* hdlname = "u_test ap_condition_75" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:71.8-71.23" *)
  wire \u_test.ap_condition_75 ;
  (* hdlname = "u_test ap_condition_exit_pp0_iter0_stage0" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:46.8-46.42" *)
  wire \u_test.ap_condition_exit_pp0_iter0_stage0 ;
  (* hdlname = "u_test ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:49.8-49.56" *)
  wire \u_test.ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg ;
  (* hdlname = "u_test ap_continue_int" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:64.9-64.24" *)
  wire \u_test.ap_continue_int ;
  (* hdlname = "u_test ap_done" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:29.10-29.17" *)
  wire \u_test.ap_done ;
  (* hdlname = "u_test ap_done_int" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:65.8-65.19" *)
  wire \u_test.ap_done_int ;
  (* hdlname = "u_test ap_done_reg" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:63.8-63.19" *)
  wire \u_test.ap_done_reg ;
  (* hdlname = "u_test ap_done_sig" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:70.9-70.20" *)
  wire \u_test.ap_done_sig ;
  (* hdlname = "u_test ap_enable_reg_pp0_iter0" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:41.9-41.32" *)
  wire \u_test.ap_enable_reg_pp0_iter0 ;
  (* hdlname = "u_test ap_enable_reg_pp0_iter1" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:42.8-42.31" *)
  wire \u_test.ap_enable_reg_pp0_iter1 ;
  (* hdlname = "u_test ap_loop_exit_ready" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:47.9-47.27" *)
  wire \u_test.ap_loop_exit_ready ;
  (* hdlname = "u_test ap_loop_exit_ready_delayed" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:51.8-51.34" *)
  wire \u_test.ap_loop_exit_ready_delayed ;
  (* hdlname = "u_test ap_loop_exit_ready_pp0_iter1_reg" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:62.8-62.40" *)
  wire \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  (* hdlname = "u_test ap_loop_init" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:56.9-56.21" *)
  wire \u_test.ap_loop_init ;
  (* hdlname = "u_test ap_ready" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:31.10-31.18" *)
  wire \u_test.ap_ready ;
  (* hdlname = "u_test ap_ready_int" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:48.8-48.20" *)
  wire \u_test.ap_ready_int ;
  (* hdlname = "u_test ap_ready_sig" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:69.9-69.21" *)
  wire \u_test.ap_ready_sig ;
  (* hdlname = "u_test ap_return" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:35.16-35.25" *)
  wire [12:0] \u_test.ap_return ;
  (* hdlname = "u_test ap_rst" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:27.9-27.15" *)
  wire \u_test.ap_rst ;
  (* hdlname = "u_test ap_sig_allocacmp_x1_load" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:57.13-57.37" *)
  wire [3:0] \u_test.ap_sig_allocacmp_x1_load ;
  (* hdlname = "u_test ap_start" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:28.9-28.17" *)
  wire \u_test.ap_start ;
  (* hdlname = "u_test ap_start_int" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:68.9-68.21" *)
  wire \u_test.ap_start_int ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_clk" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:28.9-28.15" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_clk ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_continue" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:35.9-35.20" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_continue ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_continue_int" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:42.9-42.24" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_continue_int ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_done" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:34.9-34.16" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_done ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_done_int" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:41.9-41.20" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_done_int ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_loop_exit_done" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:51.9-51.26" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_loop_exit_done ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_loop_exit_ready" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:49.9-49.27" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_loop_exit_ready ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_loop_exit_ready_delayed" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:50.9-50.35" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_loop_exit_ready_delayed ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_loop_init" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:45.10-45.22" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_loop_init ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_ready" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:33.9-33.17" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_ready ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_ready_int" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:40.9-40.21" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_ready_int ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_rst" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:29.9-29.15" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_rst ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_start" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:32.9-32.17" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_start ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U ap_start_int" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:38.9-38.21" *)
  wire \u_test.flow_control_loop_delay_pipe_U.ap_start_int ;
  (* hdlname = "u_test flow_control_loop_delay_pipe_U rewind_ap_ready_reg" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:56.8-56.27" *)
  wire \u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ;
  (* hdlname = "u_test out_accum2_fu_46" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:58.14-58.30" *)
  wire [11:0] \u_test.out_accum2_fu_46 ;
  (* hdlname = "u_test out_accum_fu_105_p2" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:59.21-59.40" *)
  wire [11:0] \u_test.out_accum_fu_105_p2 ;
  (* hdlname = "u_test sext_ln27_fu_101_p1" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:61.21-61.40" *)
  wire [11:0] \u_test.sext_ln27_fu_101_p1 ;
  (* hdlname = "u_test x1_fu_42" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:54.13-54.21" *)
  wire [3:0] \u_test.x1_fu_42 ;
  (* hdlname = "u_test x_fu_81_p2" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:55.14-55.24" *)
  wire [3:0] \u_test.x_fu_81_p2 ;
  (* hdlname = "u_test zext_ln26_fu_76_p1" *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:52.15-52.33" *)
  wire [63:0] \u_test.zext_ln26_fu_76_p1 ;
  (* src = "../../../test_wrapper.v:20.17-20.24" *)
  wire [7:0] \vectOut[0] ;
  (* src = "../../../test_wrapper.v:20.17-20.24" *)
  wire [7:0] \vectOut[1] ;
  (* src = "../../../test_wrapper.v:20.17-20.24" *)
  wire [7:0] \vectOut[2] ;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hff40)
  ) _048_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I3(\u_test.ap_enable_reg_pp0_iter1 ),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _049_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hbf00)
  ) _050_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I3(\u_test.x1_fu_42 [3]),
    .O(A_address0[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _051_ (
    .I0(_046_[1]),
    .I1(_046_[0]),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _052_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_000_),
    .S(ap_start)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0000000100000000)
  ) _053_ (
    .I0(\u_test.x1_fu_42 [1]),
    .I1(\u_test.x1_fu_42 [2]),
    .I2(\u_test.ap_loop_exit_ready_pp0_iter1_reg ),
    .I3(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I4(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I5(\u_test.x1_fu_42 [3]),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _054_ (
    .I0(1'h0),
    .I1(_002_),
    .O(_001_),
    .S(ap_start)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _055_ (
    .I0(_000_),
    .I1(_001_),
    .O(_029_),
    .S(\u_test.x1_fu_42 [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _056_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_003_),
    .S(\u_test.ap_loop_exit_ready_pp0_iter1_reg )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0001000000000000)
  ) _057_ (
    .I0(\u_test.x1_fu_42 [1]),
    .I1(\u_test.x1_fu_42 [2]),
    .I2(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I3(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I4(\u_test.x1_fu_42 [3]),
    .I5(\u_test.x1_fu_42 [0]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _058_ (
    .I0(_005_),
    .I1(1'h1),
    .O(_004_),
    .S(\u_test.ap_loop_exit_ready_pp0_iter1_reg )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _059_ (
    .I0(_003_),
    .I1(_004_),
    .O(_010_),
    .S(ap_start)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _060_ (
    .I0(_046_[0]),
    .I1(_046_[1]),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0001000000000000)
  ) _061_ (
    .I0(\u_test.x1_fu_42 [1]),
    .I1(\u_test.x1_fu_42 [2]),
    .I2(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I3(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I4(\u_test.x1_fu_42 [0]),
    .I5(ap_start),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _062_ (
    .I0(1'h0),
    .I1(_006_),
    .O(\u_test.ap_condition_exit_pp0_iter0_stage0 ),
    .S(\u_test.x1_fu_42 [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0001000000000000)
  ) _063_ (
    .I0(\u_test.x1_fu_42 [1]),
    .I1(\u_test.x1_fu_42 [2]),
    .I2(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I3(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I4(\u_test.x1_fu_42 [0]),
    .I5(ap_start),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _064_ (
    .I0(1'h0),
    .I1(_009_),
    .O(_007_),
    .S(\u_test.x1_fu_42 [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _065_ (
    .I0(1'h1),
    .I1(1'h1),
    .O(_008_),
    .S(\u_test.x1_fu_42 [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _066_ (
    .I0(_007_),
    .I1(_008_),
    .O(_014_),
    .S(ap_rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hbf00)
  ) _067_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I3(\u_test.x1_fu_42 [0]),
    .O(A_address0[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hbf00)
  ) _068_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I3(\u_test.x1_fu_42 [1]),
    .O(A_address0[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hbf00)
  ) _069_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I3(\u_test.x1_fu_42 [2]),
    .O(A_address0[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042304204)
  ) _070_ (
    .I0(\vectOut[1] [0]),
    .I1(\vectOut[0] [2]),
    .I2(\vectOut[2] [0]),
    .I3(_045_[2]),
    .I4(_047_[4]),
    .O(_036_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _071_ (
    .I0(\vectOut[0] [1]),
    .I1(\vectOut[1] [1]),
    .I2(\vectOut[2] [1]),
    .I3(_045_[2]),
    .I4(_047_[4]),
    .O(_036_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042304204)
  ) _072_ (
    .I0(\vectOut[1] [2]),
    .I1(\vectOut[0] [2]),
    .I2(\vectOut[2] [2]),
    .I3(_045_[2]),
    .I4(_047_[4]),
    .O(_036_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _073_ (
    .I0(\vectOut[0] [3]),
    .I1(\vectOut[1] [3]),
    .I2(\vectOut[2] [3]),
    .I3(_045_[2]),
    .I4(_047_[4]),
    .O(_036_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _074_ (
    .I0(\vectOut[0] [4]),
    .I1(\vectOut[1] [4]),
    .I2(\vectOut[2] [3]),
    .I3(_045_[2]),
    .I4(_047_[4]),
    .O(_036_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _075_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .O(A_ce0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h01)
  ) _076_ (
    .I0(_046_[0]),
    .I1(_046_[1]),
    .I2(_045_[2]),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _077_ (
    .I0(_046_[0]),
    .I1(_046_[1]),
    .I2(_045_[2]),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _078_ (
    .I0(A_q0[0]),
    .I1(\u_test.out_accum2_fu_46 [0]),
    .O(_031_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _079_ (
    .I0(A_q0[1]),
    .I1(\u_test.out_accum2_fu_46 [1]),
    .O(_031_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _080_ (
    .I0(A_q0[2]),
    .I1(\u_test.out_accum2_fu_46 [2]),
    .O(_031_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _081_ (
    .I0(A_q0[3]),
    .I1(\u_test.out_accum2_fu_46 [3]),
    .O(_031_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _082_ (
    .I0(A_q0[4]),
    .I1(\u_test.out_accum2_fu_46 [4]),
    .O(_031_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _083_ (
    .I0(A_q0[5]),
    .I1(\u_test.out_accum2_fu_46 [5]),
    .O(_031_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _084_ (
    .I0(A_q0[6]),
    .I1(\u_test.out_accum2_fu_46 [6]),
    .O(_031_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _085_ (
    .I0(A_q0[7]),
    .I1(\u_test.out_accum2_fu_46 [7]),
    .O(_031_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _086_ (
    .I0(A_q0[7]),
    .I1(\u_test.out_accum2_fu_46 [8]),
    .O(_031_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _087_ (
    .I0(A_q0[7]),
    .I1(\u_test.out_accum2_fu_46 [9]),
    .O(_031_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _088_ (
    .I0(A_q0[7]),
    .I1(\u_test.out_accum2_fu_46 [10]),
    .O(_031_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _089_ (
    .I0(A_q0[7]),
    .I1(\u_test.out_accum2_fu_46 [11]),
    .O(_031_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h40ff)
  ) _090_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .I3(\u_test.x1_fu_42 [0]),
    .O(_033_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _091_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _092_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _093_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _094_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _095_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _096_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _097_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _098_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _099_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _100_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _101_ (
    .I0(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I1(ap_start),
    .I2(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:267.31-267.87|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _102_ (
    .CI(1'h0),
    .CO(_030_[3:0]),
    .CYINIT(1'h0),
    .DI(A_q0[3:0]),
    .O(\u_test.out_accum_fu_105_p2 [3:0]),
    .S(_031_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:267.31-267.87|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _103_ (
    .CI(_030_[3]),
    .CO(_030_[7:4]),
    .CYINIT(1'h0),
    .DI(A_q0[7:4]),
    .O(\u_test.out_accum_fu_105_p2 [7:4]),
    .S(_031_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:267.31-267.87|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _104_ (
    .CI(_030_[7]),
    .CO(_030_[11:8]),
    .CYINIT(1'h0),
    .DI({ A_q0[7], A_q0[7], A_q0[7], A_q0[7] }),
    .O(\u_test.out_accum_fu_105_p2 [11:8]),
    .S(_031_[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:271.22-271.53|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _105_ (
    .CI(1'h0),
    .CO(_032_),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(\u_test.x_fu_81_p2 ),
    .S({ A_address0[3:1], _033_[0] })
  );
  BUFG _106_ (
    .I(_034_),
    .O(_044_)
  );
  BUFG _107_ (
    .I(_035_),
    .O(\u_test.ap_clk )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _108_ (
    .C(_044_),
    .CE(_015_),
    .D(_042_[0]),
    .Q(\stimIn[0] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _109_ (
    .C(_044_),
    .CE(_015_),
    .D(_042_[1]),
    .Q(\stimIn[0] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _110_ (
    .C(_044_),
    .CE(_016_),
    .D(_042_[0]),
    .Q(\stimIn[1] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _111_ (
    .C(_044_),
    .CE(_016_),
    .D(_042_[1]),
    .Q(\stimIn[1] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _112_ (
    .C(_044_),
    .CE(_016_),
    .D(_042_[2]),
    .Q(\stimIn[1] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _113_ (
    .C(_044_),
    .CE(_016_),
    .D(_042_[3]),
    .Q(\stimIn[1] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _114_ (
    .C(_044_),
    .CE(_016_),
    .D(_042_[4]),
    .Q(\stimIn[1] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _115_ (
    .C(_044_),
    .CE(_016_),
    .D(_042_[5]),
    .Q(\stimIn[1] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _116_ (
    .C(_044_),
    .CE(_016_),
    .D(_042_[6]),
    .Q(\stimIn[1] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _117_ (
    .C(_044_),
    .CE(_016_),
    .D(_042_[7]),
    .Q(\stimIn[1] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _118_ (
    .C(_044_),
    .CE(_013_),
    .D(_036_[0]),
    .Q(_043_[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _119_ (
    .C(_044_),
    .CE(_013_),
    .D(_036_[1]),
    .Q(_043_[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _120_ (
    .C(_044_),
    .CE(_013_),
    .D(_036_[2]),
    .Q(_043_[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _121_ (
    .C(_044_),
    .CE(_013_),
    .D(_036_[3]),
    .Q(_043_[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _122_ (
    .C(_044_),
    .CE(_013_),
    .D(_036_[4]),
    .Q(_043_[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _123_ (
    .C(_044_),
    .CE(1'h1),
    .D(_040_),
    .Q(_043_[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _124_ (
    .C(_044_),
    .CE(1'h1),
    .D(_037_),
    .Q(_043_[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _125_ (
    .C(_044_),
    .CE(1'h1),
    .D(_038_),
    .Q(_043_[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _126_ (
    .C(_044_),
    .CE(1'h1),
    .D(_039_),
    .Q(\vectOut[0] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _127_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.ap_loop_exit_ready_pp0_iter1_reg ),
    .Q(\vectOut[0] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _128_ (
    .C(_044_),
    .CE(_012_),
    .D(A_ce0),
    .Q(\vectOut[0] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _129_ (
    .C(_044_),
    .CE(_012_),
    .D(A_address0[0]),
    .Q(\vectOut[0] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _130_ (
    .C(_044_),
    .CE(_012_),
    .D(A_address0[1]),
    .Q(\vectOut[0] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _131_ (
    .C(_044_),
    .CE(_012_),
    .D(A_address0[2]),
    .Q(\vectOut[0] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _132_ (
    .C(_044_),
    .CE(_012_),
    .D(A_address0[3]),
    .Q(\vectOut[0] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _133_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [0]),
    .Q(\vectOut[1] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _134_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [1]),
    .Q(\vectOut[1] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _135_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [2]),
    .Q(\vectOut[1] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _136_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [3]),
    .Q(\vectOut[1] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _137_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [4]),
    .Q(\vectOut[1] [4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _138_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [5]),
    .Q(\vectOut[1] [5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _139_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [6]),
    .Q(\vectOut[1] [6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _140_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [7]),
    .Q(\vectOut[1] [7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _141_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [8]),
    .Q(\vectOut[2] [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _142_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [9]),
    .Q(\vectOut[2] [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _143_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [10]),
    .Q(\vectOut[2] [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../test_wrapper.v:68.5-91.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _144_ (
    .C(_044_),
    .CE(_012_),
    .D(\u_test.out_accum_fu_105_p2 [11]),
    .Q(\vectOut[2] [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:85.1-93.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _145_ (
    .C(\u_test.ap_clk ),
    .CE(_010_),
    .D(_029_),
    .Q(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .R(ap_rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _146_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[0] [0]),
    .Q(ap_rst),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _147_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[0] [1]),
    .Q(ap_start),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _148_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[1] [0]),
    .Q(A_q0[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _149_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[1] [1]),
    .Q(A_q0[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _150_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[1] [2]),
    .Q(A_q0[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _151_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[1] [3]),
    .Q(A_q0[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _152_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[1] [4]),
    .Q(A_q0[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _153_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[1] [5]),
    .Q(A_q0[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _154_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[1] [6]),
    .Q(A_q0[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _155_ (
    .C(_044_),
    .CE(_046_[1]),
    .D(\stimIn[1] [7]),
    .Q(A_q0[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _156_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [0]),
    .Q(\u_test.out_accum2_fu_46 [0]),
    .R(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _157_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [1]),
    .Q(\u_test.out_accum2_fu_46 [1]),
    .R(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _158_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [2]),
    .Q(\u_test.out_accum2_fu_46 [2]),
    .R(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _159_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [3]),
    .Q(\u_test.out_accum2_fu_46 [3]),
    .R(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _160_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [4]),
    .Q(\u_test.out_accum2_fu_46 [4]),
    .R(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _161_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [5]),
    .Q(\u_test.out_accum2_fu_46 [5]),
    .R(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _162_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [6]),
    .Q(\u_test.out_accum2_fu_46 [6]),
    .R(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _163_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [7]),
    .Q(\u_test.out_accum2_fu_46 [7]),
    .R(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _164_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [8]),
    .Q(\u_test.out_accum2_fu_46 [8]),
    .R(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _165_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [9]),
    .Q(\u_test.out_accum2_fu_46 [9]),
    .R(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _166_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [10]),
    .Q(\u_test.out_accum2_fu_46 [10]),
    .R(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:140.1-148.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _167_ (
    .C(\u_test.ap_clk ),
    .CE(_011_),
    .D(\u_test.out_accum_fu_105_p2 [11]),
    .Q(\u_test.out_accum2_fu_46 [11]),
    .R(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:150.1-154.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _168_ (
    .C(\u_test.ap_clk ),
    .CE(A_ce0),
    .D(\u_test.x_fu_81_p2 [0]),
    .Q(\u_test.x1_fu_42 [0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:150.1-154.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _169_ (
    .C(\u_test.ap_clk ),
    .CE(A_ce0),
    .D(\u_test.x_fu_81_p2 [1]),
    .Q(\u_test.x1_fu_42 [1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:150.1-154.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _170_ (
    .C(\u_test.ap_clk ),
    .CE(A_ce0),
    .D(\u_test.x_fu_81_p2 [2]),
    .Q(\u_test.x1_fu_42 [2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:150.1-154.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _171_ (
    .C(\u_test.ap_clk ),
    .CE(A_ce0),
    .D(\u_test.x_fu_81_p2 [3]),
    .Q(\u_test.x1_fu_42 [3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:120.1-128.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _172_ (
    .C(\u_test.ap_clk ),
    .CE(1'h1),
    .D(A_ce0),
    .Q(\u_test.ap_enable_reg_pp0_iter1 ),
    .R(ap_rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test.v:130.1-138.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _173_ (
    .C(\u_test.ap_clk ),
    .CE(1'h1),
    .D(\u_test.ap_condition_exit_pp0_iter0_stage0 ),
    .Q(\u_test.ap_loop_exit_ready_pp0_iter1_reg ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../../Vitis-HLS/hls_component/test/hls/syn/verilog/test_flow_control_loop_delay_pipe.v:74.1-83.4|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'h1)
  ) _174_ (
    .C(\u_test.ap_clk ),
    .CE(A_ce0),
    .D(1'h0),
    .Q(\u_test.flow_control_loop_delay_pipe_U.ap_loop_init ),
    .S(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT6 #(
    .INIT(64'hababa8a8aba8aba8)
  ) _175_ (
    .I0(_043_[6]),
    .I1(_046_[1]),
    .I2(_046_[0]),
    .I3(\vectOut[0] [6]),
    .I4(\vectOut[1] [6]),
    .I5(_045_[2]),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT6 #(
    .INIT(64'hababa8a8aba8aba8)
  ) _176_ (
    .I0(_043_[7]),
    .I1(_046_[1]),
    .I2(_046_[0]),
    .I3(\vectOut[0] [7]),
    .I4(\vectOut[1] [7]),
    .I5(_045_[2]),
    .O(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT6 #(
    .INIT(64'ha2a2a2a2aeaea2ae)
  ) _177_ (
    .I0(\vectOut[0] [1]),
    .I1(_046_[0]),
    .I2(_046_[1]),
    .I3(ap_start),
    .I4(\u_test.flow_control_loop_delay_pipe_U.rewind_ap_ready_reg ),
    .I5(\u_test.ap_enable_reg_pp0_iter1 ),
    .O(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT6 #(
    .INIT(64'hababa8a8aba8aba8)
  ) _178_ (
    .I0(_043_[5]),
    .I1(_046_[1]),
    .I2(_046_[0]),
    .I3(\vectOut[0] [5]),
    .I4(\vectOut[1] [5]),
    .I5(_045_[2]),
    .O(_040_)
  );
  (* keep = 32'd1 *)
  IBUF _179_ (
    .I(Addr_emu[0]),
    .O(_045_[2])
  );
  (* keep = 32'd1 *)
  IBUF _180_ (
    .I(Addr_emu[1]),
    .O(_047_[4])
  );
  (* keep = 32'd1 *)
  IBUF _181_ (
    .I(Addr_emu[2]),
    .O(_041_[2])
  );
  (* keep = 32'd1 *)
  IBUF _182_ (
    .I(Din_emu[0]),
    .O(_042_[0])
  );
  (* keep = 32'd1 *)
  IBUF _183_ (
    .I(Din_emu[1]),
    .O(_042_[1])
  );
  (* keep = 32'd1 *)
  IBUF _184_ (
    .I(Din_emu[2]),
    .O(_042_[2])
  );
  (* keep = 32'd1 *)
  IBUF _185_ (
    .I(Din_emu[3]),
    .O(_042_[3])
  );
  (* keep = 32'd1 *)
  IBUF _186_ (
    .I(Din_emu[4]),
    .O(_042_[4])
  );
  (* keep = 32'd1 *)
  IBUF _187_ (
    .I(Din_emu[5]),
    .O(_042_[5])
  );
  (* keep = 32'd1 *)
  IBUF _188_ (
    .I(Din_emu[6]),
    .O(_042_[6])
  );
  (* keep = 32'd1 *)
  IBUF _189_ (
    .I(Din_emu[7]),
    .O(_042_[7])
  );
  (* keep = 32'd1 *)
  OBUF _190_ (
    .I(_043_[0]),
    .O(Dout_emu[0])
  );
  (* keep = 32'd1 *)
  OBUF _191_ (
    .I(_043_[1]),
    .O(Dout_emu[1])
  );
  (* keep = 32'd1 *)
  OBUF _192_ (
    .I(_043_[2]),
    .O(Dout_emu[2])
  );
  (* keep = 32'd1 *)
  OBUF _193_ (
    .I(_043_[3]),
    .O(Dout_emu[3])
  );
  (* keep = 32'd1 *)
  OBUF _194_ (
    .I(_043_[4]),
    .O(Dout_emu[4])
  );
  (* keep = 32'd1 *)
  OBUF _195_ (
    .I(_043_[5]),
    .O(Dout_emu[5])
  );
  (* keep = 32'd1 *)
  OBUF _196_ (
    .I(_043_[6]),
    .O(Dout_emu[6])
  );
  (* keep = 32'd1 *)
  OBUF _197_ (
    .I(_043_[7]),
    .O(Dout_emu[7])
  );
  (* keep = 32'd1 *)
  IBUF _198_ (
    .I(clk_dut),
    .O(_035_)
  );
  (* keep = 32'd1 *)
  IBUF _199_ (
    .I(clk_emu),
    .O(_034_)
  );
  (* keep = 32'd1 *)
  IBUF _200_ (
    .I(get_emu),
    .O(_046_[0])
  );
  (* keep = 32'd1 *)
  IBUF _201_ (
    .I(load_emu),
    .O(_046_[1])
  );
  assign _047_[3:0] = { _045_[2], \vectOut[2] [3], \vectOut[1] [4], \vectOut[0] [4] };
  assign _045_[1:0] = { \vectOut[1] [6], \vectOut[0] [6] };
  assign _046_[2] = _045_[2];
  assign _033_[3:1] = A_address0[3:1];
  assign _041_[1:0] = { _047_[4], _045_[2] };
  assign ap_done = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign ap_ready = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign ap_return = { \u_test.out_accum_fu_105_p2 [11], \u_test.out_accum_fu_105_p2  };
  assign \u_test.A_address0  = A_address0;
  assign \u_test.A_ce0  = A_ce0;
  assign \u_test.A_ce0_local  = A_ce0;
  assign \u_test.A_q0  = A_q0;
  assign \u_test.ap_CS_fsm  = 1'h1;
  assign \u_test.ap_CS_fsm_pp0_stage0  = 1'h1;
  assign \u_test.ap_block_pp0_stage0  = 1'h0;
  assign \u_test.ap_block_pp0_stage0_11001  = 1'h0;
  assign \u_test.ap_block_pp0_stage0_subdone  = 1'h0;
  assign \u_test.ap_condition_75  = A_ce0;
  assign \u_test.ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.ap_continue_int  = 1'h1;
  assign \u_test.ap_done  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.ap_done_int  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.ap_done_reg  = 1'h0;
  assign \u_test.ap_done_sig  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.ap_enable_reg_pp0_iter0  = A_ce0;
  assign \u_test.ap_loop_exit_ready  = \u_test.ap_condition_exit_pp0_iter0_stage0 ;
  assign \u_test.ap_loop_exit_ready_delayed  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.ap_loop_init  = \u_test.flow_control_loop_delay_pipe_U.ap_loop_init ;
  assign \u_test.ap_ready  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.ap_ready_int  = A_ce0;
  assign \u_test.ap_ready_sig  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.ap_return  = { \u_test.out_accum_fu_105_p2 [11], \u_test.out_accum_fu_105_p2  };
  assign \u_test.ap_rst  = ap_rst;
  assign \u_test.ap_sig_allocacmp_x1_load  = A_address0;
  assign \u_test.ap_start  = ap_start;
  assign \u_test.ap_start_int  = A_ce0;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_clk  = \u_test.ap_clk ;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_continue  = 1'h1;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_continue_int  = 1'h1;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_done  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_done_int  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_loop_exit_done  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_loop_exit_ready  = \u_test.ap_condition_exit_pp0_iter0_stage0 ;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_loop_exit_ready_delayed  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_ready  = \u_test.ap_loop_exit_ready_pp0_iter1_reg ;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_ready_int  = A_ce0;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_rst  = ap_rst;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_start  = ap_start;
  assign \u_test.flow_control_loop_delay_pipe_U.ap_start_int  = A_ce0;
  assign \u_test.sext_ln27_fu_101_p1  = { A_q0[7], A_q0[7], A_q0[7], A_q0[7], A_q0 };
  assign \u_test.zext_ln26_fu_76_p1  = { 60'h000000000000000, A_address0 };
  assign \vectOut[0] [0] = \vectOut[0] [2];
  assign \vectOut[2] [7:4] = { 3'hx, \vectOut[2] [3] };
endmodule
