read_liberty -min /usr/local/share/qflow/tech/etri050/etri05_stdcells.lib
read_liberty -max /usr/local/share/qflow/tech/etri050/etri05_stdcells.lib
read_verilog apple_1_WozMon_PIA.rtlnopwr.v
link_design apple_1_WozMon_PIA
read_sdc apple_1_WozMon_PIA.sdc
check_setup
report_annotated_check
report_annotated_delay
report_checks -path_delay min_max -group_count 1000
exit
