M48
; DRILL file {KiCad 9.0.1-9.0.1-0~ubuntu24.04.1} date 2025-04-22T11:48:04+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-22T11:48:04+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-9.0.1-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X93.0Y-41.0
X95.0Y-160.0
X147.5Y-41.0
X147.5Y-160.0
M30
