#!/usr/bin/bash

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/bin
export PATH=/opt/Gowin/IDE/bin:/opt/Gowin/Programmer/bin:$PATH
export LD_LIBRARY_PATH=/opt/Gowin/IDE/lib:/opt/Gowin/Programmer/bin:$LD_LIBRARY_PATH

unset SESSION_MANAGER

