M48
; DRILL file {KiCad 9.0.1-9.0.1-0~ubuntu24.04.1} date 2025-04-22T11:37:26+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-22T11:37:26+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-9.0.1-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X164.0Y-92.0
X164.0Y-154.0
X230.0Y-92.0
X230.0Y-154.0
M30
