-d /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/ALU8/emulation/GoWin/impl/gwsynthesis/ALU_wrapper.vg
-p GW5A-25B-MBGA121N-2
-pn GW5A-LV25MG121NC2/I1
-cst /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/ALU8/emulation/GoWin/src/ALU_wrapper.cst
-cfg /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/ALU8/emulation/GoWin/impl/pnr/device.cfg
-sdc /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/ALU8/emulation/GoWin/src/ALU_wrapper.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
