-d /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/FIR8/2_Splited_IO/emulation/Gowin/fir_pe_wrapper/impl/gwsynthesis/fir_pe_wrapper.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/FIR8/2_Splited_IO/emulation/Gowin/fir_pe_wrapper/src/psce_wrapper.cst
-cfg /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/FIR8/2_Splited_IO/emulation/Gowin/fir_pe_wrapper/impl/pnr/device.cfg
-sdc /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/FIR8/2_Splited_IO/emulation/Gowin/fir_pe_wrapper/src/psce_wrapper.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
