;
; File generated by cc65 v 2.13.3
;
	.fopt		compiler,"cc65 v 2.13.3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.import		_putchar
	.export		_main

.segment	"RODATA"

L0001:
	.byte	$25,$73,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"RODATA"

L0006:
	.byte	$48,$65,$6C,$6C,$6F,$20,$57,$6F,$72,$6C,$64,$0A,$00

.segment	"BSS"

L0003:
	.res	2,$00
L0005:
	.res	13,$00

.segment	"CODE"

;
; int i = 0;
;
	lda     #$00
	sta     L0003
	sta     L0003+1
;
; char szBuff[] = "Hello World\n";
;
	ldy     #$0C
L0007:	lda     L0006,y
	sta     L0005,y
	dey
	bpl     L0007
;
; printf("%s", szBuff);
;
	lda     #<(L0001)
	ldx     #>(L0001)
	jsr     pushax
	lda     #<(L0005)
	ldx     #>(L0005)
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; if (szBuff[i])
;
L000B:	lda     #<(L0005)
	sta     ptr1
	lda     #>(L0005)
	clc
	adc     L0003+1
	sta     ptr1+1
	ldy     L0003
	lda     (ptr1),y
	beq     L000C
;
; putchar(szBuff[i]);
;
	lda     #<(L0005)
	sta     ptr1
	lda     #>(L0005)
	clc
	adc     L0003+1
	sta     ptr1+1
	ldy     L0003
	lda     (ptr1),y
	ldx     #$00
	jsr     _putchar
;
; i++;
;
	lda     L0003
	ldx     L0003+1
	jsr     incax1
	sta     L0003
	stx     L0003+1
;
; }
;
	jmp     L000B
;
; return 0;
;
L000C:	tax
;
; }
;
	rts

.endproc

