-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    clear : IN STD_LOGIC_VECTOR (0 downto 0);
    start_r : IN STD_LOGIC_VECTOR (0 downto 0);
    hh : OUT STD_LOGIC_VECTOR (7 downto 0);
    mm : OUT STD_LOGIC_VECTOR (7 downto 0);
    ss : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of FIR8 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "FIR8_FIR8,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a100t-csg324-2I,HLS_INPUT_CLOCK=1000.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.883214,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=18,HLS_SYN_LUT=167,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_3B : STD_LOGIC_VECTOR (5 downto 0) := "111011";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

    signal p_ss : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_mm : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_hh : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_phi_mux_p_ss_loc_2_phi_fu_90_p10 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal clear_read_read_fu_60_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal start_r_read_read_fu_54_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln59_fu_162_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln44_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_p_mm_loc_3_phi_fu_108_p10 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln56_fu_187_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_mux_p_hh_loc_3_phi_fu_125_p10 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln50_fu_218_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln50_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln53_fu_212_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_condition_53 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    p_hh_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_hh <= ap_const_lv5_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    if ((clear_read_read_fu_60_p2 = ap_const_lv1_1)) then 
                        p_hh <= ap_const_lv5_0;
                    elsif ((ap_const_boolean_1 = ap_condition_53)) then 
                        p_hh <= select_ln50_fu_218_p3;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    p_mm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_mm <= ap_const_lv6_0;
            else
                if ((((icmp_ln47_fu_181_p2 = ap_const_lv1_1) and (icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((clear_read_read_fu_60_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                    p_mm <= ap_const_lv6_0;
                elsif (((icmp_ln47_fu_181_p2 = ap_const_lv1_0) and (icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    p_mm <= add_ln56_fu_187_p2;
                end if; 
            end if;
        end if;
    end process;


    p_ss_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_ss <= ap_const_lv6_0;
            else
                if ((((icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((clear_read_read_fu_60_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                    p_ss <= ap_const_lv6_0;
                elsif (((icmp_ln44_fu_156_p2 = ap_const_lv1_0) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    p_ss <= add_ln59_fu_162_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln53_fu_212_p2 <= std_logic_vector(unsigned(p_hh) + unsigned(ap_const_lv5_1));
    add_ln56_fu_187_p2 <= std_logic_vector(unsigned(p_mm) + unsigned(ap_const_lv6_1));
    add_ln59_fu_162_p2 <= std_logic_vector(unsigned(p_ss) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_condition_53_assign_proc : process(clear_read_read_fu_60_p2, start_r_read_read_fu_54_p2, icmp_ln44_fu_156_p2, icmp_ln47_fu_181_p2)
    begin
                ap_condition_53 <= ((icmp_ln47_fu_181_p2 = ap_const_lv1_1) and (icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0));
    end process;


    ap_phi_mux_p_hh_loc_3_phi_fu_125_p10_assign_proc : process(p_hh, ap_CS_fsm_state1, clear_read_read_fu_60_p2, start_r_read_read_fu_54_p2, icmp_ln44_fu_156_p2, icmp_ln47_fu_181_p2, select_ln50_fu_218_p3)
    begin
        if (((icmp_ln47_fu_181_p2 = ap_const_lv1_1) and (icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_p_hh_loc_3_phi_fu_125_p10 <= select_ln50_fu_218_p3;
        elsif ((((icmp_ln47_fu_181_p2 = ap_const_lv1_0) and (icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln44_fu_156_p2 = ap_const_lv1_0) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((start_r_read_read_fu_54_p2 = ap_const_lv1_0) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_p_hh_loc_3_phi_fu_125_p10 <= p_hh;
        elsif (((clear_read_read_fu_60_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_p_hh_loc_3_phi_fu_125_p10 <= ap_const_lv5_0;
        else 
            ap_phi_mux_p_hh_loc_3_phi_fu_125_p10 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_p_mm_loc_3_phi_fu_108_p10_assign_proc : process(p_mm, ap_CS_fsm_state1, clear_read_read_fu_60_p2, start_r_read_read_fu_54_p2, icmp_ln44_fu_156_p2, icmp_ln47_fu_181_p2, add_ln56_fu_187_p2)
    begin
        if (((icmp_ln47_fu_181_p2 = ap_const_lv1_0) and (icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_p_mm_loc_3_phi_fu_108_p10 <= add_ln56_fu_187_p2;
        elsif ((((icmp_ln44_fu_156_p2 = ap_const_lv1_0) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((start_r_read_read_fu_54_p2 = ap_const_lv1_0) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_p_mm_loc_3_phi_fu_108_p10 <= p_mm;
        elsif ((((icmp_ln47_fu_181_p2 = ap_const_lv1_1) and (icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((clear_read_read_fu_60_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_p_mm_loc_3_phi_fu_108_p10 <= ap_const_lv6_0;
        else 
            ap_phi_mux_p_mm_loc_3_phi_fu_108_p10 <= "XXXXXX";
        end if; 
    end process;


    ap_phi_mux_p_ss_loc_2_phi_fu_90_p10_assign_proc : process(p_ss, ap_CS_fsm_state1, clear_read_read_fu_60_p2, start_r_read_read_fu_54_p2, add_ln59_fu_162_p2, icmp_ln44_fu_156_p2, icmp_ln47_fu_181_p2)
    begin
        if (((icmp_ln44_fu_156_p2 = ap_const_lv1_0) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_p_ss_loc_2_phi_fu_90_p10 <= add_ln59_fu_162_p2;
        elsif (((start_r_read_read_fu_54_p2 = ap_const_lv1_0) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_p_ss_loc_2_phi_fu_90_p10 <= p_ss;
        elsif ((((icmp_ln47_fu_181_p2 = ap_const_lv1_1) and (icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln47_fu_181_p2 = ap_const_lv1_0) and (icmp_ln44_fu_156_p2 = ap_const_lv1_1) and (start_r_read_read_fu_54_p2 = ap_const_lv1_1) and (clear_read_read_fu_60_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((clear_read_read_fu_60_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_p_ss_loc_2_phi_fu_90_p10 <= ap_const_lv6_0;
        else 
            ap_phi_mux_p_ss_loc_2_phi_fu_90_p10 <= "XXXXXX";
        end if; 
    end process;

    clear_read_read_fu_60_p2 <= clear;
    hh <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_p_hh_loc_3_phi_fu_125_p10),8));
    icmp_ln44_fu_156_p2 <= "1" when (p_ss = ap_const_lv6_3B) else "0";
    icmp_ln47_fu_181_p2 <= "1" when (p_mm = ap_const_lv6_3B) else "0";
    icmp_ln50_fu_206_p2 <= "1" when (p_hh = ap_const_lv5_17) else "0";
    mm <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_p_mm_loc_3_phi_fu_108_p10),8));
    select_ln50_fu_218_p3 <= 
        ap_const_lv5_0 when (icmp_ln50_fu_206_p2(0) = '1') else 
        add_ln53_fu_212_p2;
    ss <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_p_ss_loc_2_phi_fu_90_p10),8));
    start_r_read_read_fu_54_p2 <= start_r;
end behav;
