/*******************************************************************************
Vendor: GoodKook, goodkook@gmail.com
Associated Filename: CPU_6502.h
Purpose: SC wrapper for Verilog 6502 CPU
Revision History: Jan. 5, 2024
*******************************************************************************/
#ifndef _CPU_6502_H_
#define _CPU_6502_H_

#include "systemc.h"

/*******************************************************************************
Purpose: SystemC wrapper for Arlet's Verilog-6502
         Generated by MTI's genscmod -bool -sc_bv cpu > cpu.h
*******************************************************************************/
class CPU_6502 : public sc_foreign_module
{
public:
    sc_in<bool> clk;
    sc_in<bool> reset;
    sc_out<sc_bv<16> > AB;
    sc_in<sc_bv<8> > DI;
    sc_out<sc_bv<8> > DO;
    sc_out<bool> WE;
    sc_in<bool> IRQ;
    sc_in<bool> NMI;
    sc_in<bool> RDY;

    CPU_6502(sc_module_name nm) : sc_foreign_module(nm, "cpu"),
        clk("clk"),
        reset("reset"),
        AB("AB"),
        DI("DI"),
        DO("DO"),
        WE("WE"),
        IRQ("IRQ"),
        NMI("NMI"),
        RDY("RDY")
    {
    }
    ~CPU_6502()
    {}

};

#endif
