-d /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/CPU_6502/emulation/Gowin/cpu_wrapper_RT/impl/gwsynthesis/cpu_wrapper_RT.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/CPU_6502/emulation/Gowin/cpu_wrapper_RT/src/cpu_wrapper.cst
-cfg /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/CPU_6502/emulation/Gowin/cpu_wrapper_RT/impl/pnr/device.cfg
-sdc /home/goodkook/ETRI050_DesignKit/devel/Ref_Design/CPU_6502/emulation/Gowin/cpu_wrapper_RT/src/cpu_wrapper.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
